/* FaxClip analytics (TikTok public stats every 12 h) and link generator with short links. */
(function(){
const N=x=>x==null?"—":Number(x).toLocaleString("ru-RU");
const fmt=t=>t?new Date(typeof t==="number"?t*1000:t).toLocaleString("ru-RU",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"—";
const v=id=>{const e=document.getElementById(id);return e?(e.type==="checkbox"?e.checked:e.value.trim()):""};
const errBox='<p id="wsErr" class="ws-err" style="display:none"></p>';
const fail=e=>{const b=document.getElementById("wsErr");if(b){b.textContent=e.message||String(e);b.style.display="block"}else showAppError(e)};
const opt=(val,l,cur)=>`<option value="${esc(val)}" ${String(val)===String(cur)?"selected":""}>${esc(l)}</option>`;
const AN={days:30,account:"",metric:"views"};
function chart(series,key){const W=760,H=200,P=28;const vals=series.map(s=>s[key]||0),max=Math.max(1,...vals),min=Math.min(...vals);
 const lo=key==="followers"?min*0.98:0,span=Math.max(1,max-lo);const x=i=>P+i*(W-2*P)/Math.max(1,series.length-1),y=val=>H-P-((val-lo)/span)*(H-2*P);
 const pts=vals.map((val,i)=>`${x(i).toFixed(1)},${y(val).toFixed(1)}`).join(" ");const pm=Math.max(1,...series.map(s=>s.posted));
 const bars=series.map((s,i)=>s.posted?`<rect x="${(x(i)-3).toFixed(1)}" y="${(H-P-s.posted/pm*30).toFixed(1)}" width="6" height="${(s.posted/pm*30).toFixed(1)}" rx="2" fill="rgba(198,255,61,.35)"><title>${s.day}: публикаций ${s.posted}</title></rect>`:"").join("");
 const lab=[0,Math.floor(series.length/2),series.length-1].map(i=>`<text x="${x(i)}" y="${H-6}" fill="#8d958f" font-size="11" text-anchor="middle">${series[i].day.slice(5).split("-").reverse().join(".")}</text>`).join("");
 return `<svg viewBox="0 0 ${W} ${H}" style="width:100%;height:auto"><defs><linearGradient id="anG" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#c6ff3d" stop-opacity=".35"/><stop offset="1" stop-color="#c6ff3d" stop-opacity="0"/></linearGradient></defs>
 <line x1="${P}" x2="${W-P}" y1="${H-P}" y2="${H-P}" stroke="rgba(255,255,255,.1)"/>${bars}<polygon points="${P},${H-P} ${pts} ${W-P},${H-P}" fill="url(#anG)"/><polyline points="${pts}" fill="none" stroke="#c6ff3d" stroke-width="2.5" stroke-linejoin="round"/>
 <text x="${P}" y="14" fill="#8d958f" font-size="11">${N(max)}</text>${lab}</svg>`}
async function page(){const q=new URLSearchParams({days:AN.days});if(AN.account)q.set("account_id",AN.account);
 const [r,acc]=await Promise.all([api("/analytics/v2?"+q),api("/accounts")]);const t=r.totals;
 const card=(l,val,sub)=>`<div class="card"><span class="muted" style="font-size:13px">${l}</span><div class="stat-value" style="font-size:28px;font-weight:800;margin-top:6px">${N(val)}</div>${sub?`<div class="muted">${sub}</div>`:""}</div>`;
 const f7=r.accounts.reduce((s,a)=>s+(a.followers_7d||0),0);
 shell("Аналитика","Статистика TikTok по аккаунтам и роликам",`
 <div class="row" style="flex-wrap:wrap;gap:10px;margin-bottom:12px"><div class="row form ws-filter" style="gap:8px"><select onchange="anSet('days',this.value)">${[7,30,90].map(d=>opt(d,"За "+d+" дней",AN.days)).join("")}</select><select onchange="anSet('account',this.value)">${opt("","Все аккаунты",AN.account)}${acc.map(a=>opt(a.id,a.platform+" · "+(a.username||"—"),AN.account)).join("")}</select></div>
 <div class="row" style="gap:8px"><span class="muted">${r.syncing?"Обновляю… "+esc(r.progress||""):"Обновлено: "+fmt(r.last_sync)+" · раз в 12 ч"}</span><button class="btn secondary" onclick="anSync(this)" ${r.syncing?"disabled":""}>Обновить сейчас</button></div></div>
 ${r.last_error?`<p class="ws-err" style="display:block">Не всё удалось обновить: ${esc(r.last_error)}. Если TikTok не отдаёт цифры серверу, впишите их вручную у ролика.</p>`:""}
 <div class="grid">${card("Просмотры",t.views,"по "+t.videos+" роликам")}${card("Лайки",t.likes,"")}${card("Комментарии",t.comments,"репостов "+N(t.shares)+" · сохранений "+N(t.saves))}${card("Подписчики",t.followers,f7?(f7>0?"+":"")+N(f7)+" за 7 дней":"")}</div>
 <div class="card" style="margin-top:14px"><div class="row"><b>Динамика</b><div class="tabs ws-tabs" style="margin:0">${[["views","Просмотры"],["likes","Лайки"],["followers","Подписчики"]].map(([k,l])=>`<button class="${AN.metric===k?"active":""}" onclick="anSet('metric','${k}')">${l}</button>`).join("")}</div></div>${chart(r.series,AN.metric)}<p class="muted">Столбики — дни с публикациями.</p></div>
 <div class="grid2" style="margin-top:14px"><div class="card"><b>Аккаунты</b><table class="table"><thead><tr><th>Аккаунт</th><th>Подписчики</th><th>За 7 дней</th><th>Лайков всего</th><th>Просмотры</th></tr></thead><tbody>${r.accounts.map(a=>`<tr><td><b>${esc(a.username||"—")}</b><br><span class="muted">${esc(a.platform||"")}${a.videos!=null?" · видео "+a.videos:""}</span></td><td>${N(a.followers)}</td><td>${a.followers_7d==null?"—":(a.followers_7d>0?"+":"")+N(a.followers_7d)}</td><td>${N(a.hearts)}</td><td>${N(a.views)}</td></tr>`).join("")||'<tr><td colspan="5" class="empty">Нет аккаунтов</td></tr>'}</tbody></table></div>
 <div class="card"><b>Топ роликов</b><table class="table"><thead><tr><th>Ролик</th><th>Просмотры</th><th>Лайки</th><th>Комм.</th><th></th></tr></thead><tbody>${r.top.map(x=>`<tr><td><b>${esc((x.caption||"Видео").slice(0,50))}</b><br><span class="muted">${esc(x.username||"")} · ${fmt(x.published_at)}${x.source==="manual"?" · вручную":""}</span></td><td>${N(x.views)}</td><td>${N(x.likes)}</td><td>${N(x.comments)}</td><td><a class="btn secondary" href="${esc(x.url)}" target="_blank" rel="noopener">Открыть</a> <button class="btn secondary" onclick="anManual('${x.publication_id}')">Вписать</button></td></tr>`).join("")||'<tr><td colspan="5" class="empty">Пока нет опубликованных роликов со статистикой</td></tr>'}</tbody></table>
 ${r.no_metrics.length?`<p class="muted" style="margin-top:10px">Ещё без статистики: ${r.no_metrics.length}. ${r.no_metrics.slice(0,5).map(x=>`<a href="#" onclick="anManual('${x.publication_id}');return false">${esc((x.caption||"видео").slice(0,24))}</a>`).join(", ")}</p>`:""}</div></div>
 <p class="muted" style="margin-top:12px">Цифры берутся с публичных страниц TikTok — без пароля и без официального API. Instagram и YouTube через официальный API подключим, когда будут ключи приложений.</p>`)}
window.anSet=(k,val)=>{AN[k]=k==="days"?+val:val;page().catch(showAppError)};
window.anSync=async btn=>{btn.disabled=true;try{await api("/analytics/sync",{method:"POST",body:"{}"});setTimeout(()=>page().catch(()=>{}),1500)}catch(e){showAppError(e)}};
window.anManual=pid=>modalBox(`<h3>Статистика ролика вручную</h3><p class="muted">Откройте ролик в TikTok и перепишите цифры. Они сохранятся в истории.</p><div class="form"><div class="formgrid"><label>Просмотры<input id="mV" type="number" min="0"></label><label>Лайки<input id="mL" type="number" min="0"></label></div><div class="formgrid"><label>Комментарии<input id="mC" type="number" min="0"></label><label>Репосты<input id="mS" type="number" min="0"></label></div><label>Сохранения<input id="mF" type="number" min="0"></label>${errBox}<div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="anManualSave('${pid}')">Сохранить</button></div></div>`);
window.anManualSave=async pid=>{try{await api("/analytics/manual",{method:"POST",body:JSON.stringify({publication_id:pid,views:+v("mV"),likes:+v("mL"),comments:+v("mC"),shares:+v("mS"),saves:+v("mF")})});closeModal();await page()}catch(e){fail(e)}};
/* ---------- links ---------- */
async function links(){const [r,acc]=await Promise.all([api("/links"),api("/accounts")]);const total=r.items.reduce((s,x)=>s+x.clicks,0),last14=Object.values(r.daily).reduce((s,n)=>s+n,0);
 shell("Ссылки","UTM-метки и короткие ссылки для шапки и директа",`<div class="grid">${[["Ссылок",r.items.length],["Переходов всего",total],["За 14 дней",last14]].map(([l,n])=>`<div class="card"><span class="muted" style="font-size:13px">${l}</span><div style="font-size:28px;font-weight:800;margin-top:6px">${N(n)}</div></div>`).join("")}</div>
 <div class="card" style="margin-top:14px"><div class="row" style="flex-wrap:wrap;gap:8px"><b>Все ссылки</b><div class="row" style="gap:8px"><button class="btn secondary" onclick="lnBulk()">Массово на все аккаунты</button><button class="btn secondary" onclick="lnExport(this)">Выгрузить CSV</button></div></div>
 <table class="table"><thead><tr><th>Ссылка</th><th>Место</th><th>Короткая</th><th>Переходы</th><th></th></tr></thead><tbody>${r.items.map(x=>`<tr><td><b>${esc(x.name)}</b><br><span class="muted" style="word-break:break-all">${esc(x.full_url.slice(0,110))}${x.full_url.length>110?"…":""}</span>${x.metrika_goal?`<div class="muted">Цель Метрики: ${esc(x.metrika_goal)}</div>`:""}</td><td>${esc(x.placement_name)}</td><td><code style="word-break:break-all">${esc(x.short_url)}</code></td><td>${N(x.clicks)}${x.last_click_at?`<div class="muted">${fmt(x.last_click_at)}</div>`:""}</td><td><button class="btn secondary" onclick="lnCopy('${esc(x.short_url)}',this)">Копировать</button> <button class="btn secondary" onclick="lnDel('${x.id}')">Удалить</button></td></tr>`).join("")||'<tr><td colspan="5" class="empty">Ссылок пока нет</td></tr>'}</tbody></table></div>
 <p class="muted" style="margin-top:12px">Короткая ссылка ведёт через FaxClip и считает переходы, затем открывает вашу страницу с метками utm_source (сеть), utm_medium (место), utm_campaign (оффер), utm_content (аккаунт), utm_term (ключевое слово) — их видно в Яндекс.Метрике. На бесплатном сервере первый переход после простоя может открываться 20–40 секунд.</p>`,
 `<button class="btn" onclick="lnForm()">+ Ссылка</button>`);window._lnAcc=acc;window._lnPl=r.placements}
const fields=(pl,acc,one)=>`<label>Куда ведёт (ваша страница)<input id="lT" placeholder="https://site.ru/offer"></label>
 <div class="formgrid"><label>Сеть<select id="lN">${["tiktok","instagram","youtube","vk","telegram"].map(n=>opt(n,n)).join("")}</select></label>${one?`<label>Место<select id="lP">${Object.entries(pl).map(([k,l])=>opt(k,l,"shapka")).join("")}</select></label>`:""}</div>
 ${one?`<label>Аккаунт (страница)<select id="lA">${opt("","— не привязывать —")}${acc.map(a=>opt(a.id,(a.username||"—")+" · "+a.platform)).join("")}</select></label>`:`<b>Места</b><div class="row" style="justify-content:flex-start;gap:12px;flex-wrap:wrap">${Object.entries(pl).map(([k,l])=>`<label class="ws-check"><input type="checkbox" class="lPl" value="${k}" ${["shapka","direct"].includes(k)?"checked":""}> ${l}</label>`).join("")}</div>`}
 <div class="formgrid"><label>Оффер (кампания)<input id="lO" placeholder="kurs_avto"></label><label>Ключевое слово<input id="lK" placeholder="ремонт"></label></div>
 <label>Цель Яндекс.Метрики (для отчёта)<input id="lG" placeholder="lead"></label>`;
window.lnForm=()=>{modalBox(`<h3>Новая ссылка</h3><div class="form">${fields(window._lnPl,window._lnAcc,true)}<label>Название (необязательно)<input id="lNm"></label>${errBox}<div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="lnSave()">Создать</button></div></div>`)};
window.lnSave=async()=>{try{const r=await api("/links",{method:"POST",body:JSON.stringify({target_url:v("lT"),network:v("lN"),placement:v("lP"),account_id:v("lA")||null,offer:v("lO"),keyword:v("lK"),metrika_goal:v("lG"),name:v("lNm")})});await links();modalBox(`<h3>Ссылка готова</h3><p><code style="word-break:break-all">${esc(r.short_url)}</code></p><p class="muted" style="word-break:break-all">${esc(r.full_url)}</p><div class="row"><button class="btn secondary" onclick="lnCopy('${esc(r.short_url)}',this)">Копировать</button><button class="btn" onclick="closeModal()">Готово</button></div>`)}catch(e){fail(e)}};
window.lnBulk=()=>{modalBox(`<h3>Ссылки для всех аккаунтов</h3><p class="muted">Для каждого аккаунта создаётся своя ссылка на каждое место — в отчёте видно, какой аккаунт и где привёл человека.</p><div class="form">${fields(window._lnPl,window._lnAcc,false)}${errBox}<div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="lnBulkSave()">Создать</button></div></div>`)};
window.lnBulkSave=async()=>{try{const r=await api("/links/bulk",{method:"POST",body:JSON.stringify({target_url:v("lT"),network:v("lN"),offer:v("lO"),keyword:v("lK"),metrika_goal:v("lG"),placements:[...document.querySelectorAll(".lPl:checked")].map(x=>x.value)})});closeModal();await links();modalBox(`<h3>Создано ссылок: ${r.created}</h3><p>Выгрузите их файлом кнопкой «Выгрузить CSV».</p><div class="row"><button class="btn" onclick="closeModal()">Понятно</button></div>`)}catch(e){fail(e)}};
window.lnCopy=(u,btn)=>navigator.clipboard.writeText(u).then(()=>{btn.textContent="Скопировано"}).catch(()=>prompt("Скопируйте ссылку",u));
window.lnDel=async id=>{if(!confirm("Удалить ссылку? Переходы по ней перестанут работать."))return;await api("/links/"+id,{method:"DELETE"});await links()};
window.lnExport=async btn=>{btn.disabled=true;try{await localLogin;const r=await fetch("/api/links/export.csv",{headers:authHeaders()});if(!r.ok)throw new Error("Не удалось выгрузить");const u=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=u;a.download="faxclip-links.csv";a.click();setTimeout(()=>URL.revokeObjectURL(u),4000)}catch(e){showAppError(e)}finally{btn.disabled=false}};
routes.analytics=page;window.analytics=page;routes.links=links;
const navEl=document.querySelector("nav");if(navEl&&!navEl.querySelector('[data-page="links"]')){const b=document.createElement("button");b.type="button";b.className="nav-item";b.dataset.page="links";b.innerHTML='<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><path d="M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1"/><path d="M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1"/></svg><span>Ссылки</span>';b.onclick=()=>goPage("links");const ref=navEl.querySelector('[data-page="registration"]');ref?ref.before(b):navEl.append(b)}
})();
