
const $=s=>document.querySelector(s), view=$("#view"), modal=$("#modal");
const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
function authHeaders(extra={}){return {"X-Telegram-Init-Data":tg?.initData||"",...extra}}
async function api(path,opt={}){const r=await fetch("/api"+path,{...opt,headers:authHeaders({"Content-Type":"application/json",...(opt.headers||{})})});const x=await r.json();if(!r.ok)throw new Error(x.error||`HTTP ${r.status}`);return x}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function pct(a,b){return b?Math.min(100,Math.round(a/b*100)):0}
function modalBox(html){modal.innerHTML=`<div class="modalbox">${html}</div>`;modal.classList.add("show")}
function closeModal(){modal.classList.remove("show")}
modal.onclick=e=>{if(e.target===modal)closeModal()}
function shell(title,sub,html,action=""){ $("#title").textContent=title;$("#subtitle").textContent=sub;$("#headerAction").innerHTML=action;view.innerHTML=html}
function metric(l,v,s=""){return `<div class="card"><div class="label">${l}</div><div class="metric">${v}</div><div class="muted" style="margin-top:6px">${s}</div></div>`}

async function dashboard(){let d=await api("/dashboard");shell("Dashboard","Единый центр управления вертикальным контентом",`
<div class="grid">${metric("Аккаунты",d.accounts,"подключено")}${metric("Устройства",d.devices,"онлайн")}${metric("Клипы",d.clips,"вертикальные 9:16")}${metric("Просмотры",d.views.toLocaleString("ru-RU"),"собрано")}</div>
<div class="grid2"><div class="card"><div class="row"><b>Динамика</b><span class="pill">Последние 12 точек</span></div><div class="chart">${[35,54,44,68,53,79,61,91,73,84,76,96].map(h=>`<i class="barcol" style="height:${h}%"></i>`).join("")}</div></div>
<div class="card"><div class="row"><b>Задачи</b><b>${d.task_percent}%</b></div><div class="progress"><div class="bar" style="width:${d.task_percent}%"></div></div><div class="muted">${d.task_done} / ${d.task_target}</div></div></div>
<div class="card" style="margin-top:14px"><div class="row"><b>Сводка</b><span class="pill"><i class="dot"></i>Система готова</span></div><div class="list"><div class="item">📤 Опубликовано клипов: <b>${d.publications}</b></div><div class="item">❤️ Лайков: <b>${d.likes.toLocaleString("ru-RU")}</b></div><div class="item">👥 Новых подписчиков: <b>${d.followers.toLocaleString("ru-RU")}</b></div></div></div>`)}
async function accounts(){let a=await api("/accounts");shell("Аккаунты","Профили, устройства и целевая аудитория",`<div class="card"><div class="row"><b>Все аккаунты</b><button class="btn" onclick="addAccount()">+ Добавить</button></div><table class="table"><thead><tr><th>Площадка</th><th>Аккаунт</th><th>Устройство</th><th>Ниша / ЦА</th><th>Статус</th><th></th></tr></thead><tbody>${a.map(x=>`<tr><td>${x.platform}</td><td><b>${x.username||"Без username"}</b></td><td>${x.device||"—"}</td><td>${x.niche||"—"}<br><span class="muted">${x.audience||""}</span></td><td><span class="pill"><i class="dot"></i>${x.status}</span></td><td><button class="btn secondary" onclick="activity('${x.id}','${x.username||x.platform}')">Активность</button></td></tr>`).join("")||`<tr><td colspan="6" class="empty">Аккаунтов пока нет</td></tr>`}</tbody></table></div>`)}
async function addAccount(){let d=await api("/devices");modalBox(`<h3>Подключить аккаунт</h3><p class="muted">Авторизацию выполняй через официальный процесс площадки на своём устройстве.</p><div class="form"><label>Площадка<select id="ap"><option>TikTok</option><option>Instagram</option><option>YouTube</option><option>VK</option></select></label><label>Username<input id="au" placeholder="@username"></label><label>Устройство<select id="ad"><option value="">Не назначено</option>${d.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}</select></label><label>Ниша<input id="an" placeholder="Beauty / Education / Gaming"></label><label>Целевая аудитория<input id="aa" placeholder="Описание ЦА"></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveAccount()">Сохранить</button></div></div>`)}
async function saveAccount(){await api("/accounts",{method:"POST",body:JSON.stringify({platform:ap.value,username:au.value,niche:an.value,audience:aa.value,device_id:ad.value||null})});closeModal();accounts()}
async function activity(id,name){let x=await api(`/accounts/${id}/activity`);modalBox(`<h3>Активность · ${name}</h3><div class="form"><label><input id="ae" type="checkbox" ${x.enabled?"checked":""}> Включить сценарий</label><div class="formgrid"><label>Роликов за сессию<input id="ai" type="number" value="${x.session_items||30}"></label><label>Лайкнуть, %<input id="al" type="number" value="${x.like_percent||15}"></label><label>Минимум просмотра, сек<input id="amin" type="number" value="${x.min_watch||5}"></label><label>Максимум просмотра, сек<input id="amax" type="number" value="${x.max_watch||20}"></label><label>Подписки, %<input id="af" type="number" value="${x.follow_percent||3}"></label><label>Расписание<input id="asch" value="${x.schedule||"09:00,14:00,20:00"}"></label></div><p class="muted">Этот экран задаёт параметры разрешённой активности. Исполнение должно использовать официально разрешённые механизмы и не обходить защиту площадок.</p><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveActivity('${id}')">Сохранить</button></div></div>`)}
async function saveActivity(id){await api(`/accounts/${id}/activity`,{method:"POST",body:JSON.stringify({enabled:ae.checked,session_items:+ai.value,min_watch:+amin.value,max_watch:+amax.value,like_percent:+al.value,follow_percent:+af.value,schedule:asch.value})});closeModal()}
async function devices(){let d=await api("/devices");shell("Устройства","Физические Android-смартфоны",`<div class="grid">${d.map(x=>`<div class="card"><div class="row"><b>📱 ${x.name}</b><span class="pill"><i class="dot ${x.status==="ONLINE"?"":"red"}"></i>${x.status}</span></div><div class="muted" style="margin-top:10px">${x.model}</div><div style="margin-top:12px">🔋 ${x.battery}%</div><div class="muted">Аккаунтов: ${x.accounts}</div><div class="muted">Token выдаётся Device Agent при подключении</div></div>`).join("")||`<div class="card empty">Нет устройств</div>`}</div><div class="card" style="margin-top:14px"><div class="row"><b>Подключение нового телефона</b><button class="btn" onclick="addDevice()">+ Добавить</button></div><p class="muted" style="margin-top:8px">Backend создаёт уникальный токен. Device Agent использует его для heartbeat и получения задач.</p></div>`)}
function addDevice(){modalBox(`<h3>Добавить устройство</h3><div class="form"><label>Название<input id="dn" value="Phone #01"></label><label>Модель<input id="dm" placeholder="Samsung Galaxy / Pixel"></label><label>Канал<select id="dc"><option>USB / ADB</option><option>LAN / ADB</option></select></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveDevice()">Создать</button></div></div>`)}
async function saveDevice(){let x=await api("/devices",{method:"POST",body:JSON.stringify({name:dn.value,model:dm.value,connection:dc.value})});closeModal();devices();setTimeout(()=>alert("Device token: "+x.device_token),100)}
async function tasks(){let t=await api("/tasks");shell("Задачи","KPI и автоматический прогресс 0–100%",`<div class="row" style="margin-bottom:14px"><span class="muted">Прогресс может увеличиваться автоматически после успешных публикаций</span><button class="btn" onclick="addTask()">+ Новая</button></div><div class="list">${t.map(x=>{let p=pct(x.done,x.target);return `<div class="card"><div class="row"><div><b>${x.title}</b><div class="muted">${x.done} / ${x.target} ${x.unit}</div></div><b>${p}%</b></div><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="row"><span class="muted">${x.deadline||"Без дедлайна"}</span><button class="btn secondary" onclick="editTask('${x.id}',${x.done},${x.target})">Изменить</button></div></div>`}).join("")||`<div class="card empty">Нет задач</div>`}</div>`)}
function addTask(){modalBox(`<h3>Новая задача</h3><div class="form"><label>Название<input id="tt" placeholder="Опубликовать 100 клипов"></label><div class="formgrid"><label>Цель<input id="tg" type="number" value="100"></label><label>Единица<input id="tu" value="клипов"></label></div><label>Период<select id="tp"><option value="DAY">День</option><option value="WEEK">Неделя</option><option value="MONTH">Месяц</option></select></label><label>Дедлайн<input id="td" type="date"></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveTask()">Создать</button></div></div>`)}
async function saveTask(){await api("/tasks",{method:"POST",body:JSON.stringify({title:tt.value,target:+tg.value,unit:tu.value,deadline:td.value,period:tp.value})});closeModal();tasks()}
function editTask(id,done,target){modalBox(`<h3>Прогресс задачи</h3><div class="form"><label>Выполнено<input id="ed" type="number" min="0" max="${target}" value="${done}"></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveTaskProgress('${id}')">Сохранить</button></div></div>`)}
async function saveTaskProgress(id){await api(`/tasks/${id}`,{method:"PATCH",body:JSON.stringify({done:+ed.value})});closeModal();tasks()}
async function content(){let c=await api("/clips");shell("Контент","Только вертикальные клипы 9:16",`<div class="card"><div class="row"><b>Клипы</b><button class="btn" onclick="addClip()">+ Создать</button></div><table class="table"><thead><tr><th>Название</th><th>Длительность</th><th>AI Score</th><th>Статус</th></tr></thead><tbody>${c.map(x=>`<tr><td>${x.title}</td><td>${Math.round(x.duration)} сек.</td><td>${x.score}/100</td><td><span class="pill">${x.status}</span></td></tr>`).join("")||`<tr><td colspan="4" class="empty">Клипов нет</td></tr>`}</tbody></table></div><div class="card" style="margin-top:14px"><b>Видео pipeline</b><div class="list"><div class="item">1. Загрузка исходного материала</div><div class="item">2. AI-анализ и выбор сильных моментов</div><div class="item">3. 9:16 + smart crop</div><div class="item">4. Субтитры + banner + hook</div><div class="item">5. Варианты → очередь публикации</div></div></div>`)}
function addClip(){modalBox(`<h3>Добавить вертикальное видео</h3><div class="form"><label>Видео<input id="cf" type="file" accept="video/*"></label><label>Название<input id="ct" value="Vertical clip"></label><div class="formgrid"><label>Длительность, сек.<input id="cd" type="number" value="30"></label><label>AI Score<input id="cs" type="number" value="0"></label></div><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveClip()">Загрузить</button></div></div>`)}
async function saveClip(){let source_file=null;if(cf.files[0]){let fd=new FormData();fd.append("file",cf.files[0]);let r=await fetch("/api/media/upload",{method:"POST",headers:authHeaders(),body:fd});let x=await r.json();if(!r.ok)throw new Error(x.error||"Upload failed");source_file=x.filename}await api("/clips",{method:"POST",body:JSON.stringify({title:ct.value,duration:+cd.value,score:+cs.value,source_file})});closeModal();content()}
async function publishing(){let p=await api("/publications");shell("Публикации","Очередь и история",`<div class="row" style="margin-bottom:14px"><span class="muted">Задания передаются назначенному устройству</span><button class="btn" onclick="addPublication()">+ В очередь</button></div><div class="card"><table class="table"><thead><tr><th>Клип</th><th>Аккаунт</th><th>Площадка</th><th>Статус</th></tr></thead><tbody>${p.map(x=>`<tr><td>${esc(x.clip)}</td><td>${esc(x.account)}</td><td>${esc(x.platform)}</td><td><span class="pill">${esc(x.status)}</span></td></tr>`).join("")||`<tr><td colspan="4" class="empty">Очередь пуста</td></tr>`}</tbody></table></div>`)}
async function addPublication(){let [c,a]=await Promise.all([api("/clips"),api("/accounts")]);modalBox(`<h3>Добавить публикацию</h3><div class="form"><label>Клип<select id="pc">${c.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("")}</select></label><label>Аккаунт<select id="pa">${a.map(x=>`<option value="${x.id}">${esc(x.platform)} · ${esc(x.username)}</option>`).join("")}</select></label><label>Дата и время<input id="ps" type="datetime-local"></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="savePublication()">Поставить в очередь</button></div></div>`) }
async function savePublication(){await api("/publications",{method:"POST",body:JSON.stringify({clip_id:pc.value,account_id:pa.value,scheduled_at:ps.value||null})});closeModal();publishing()}
async function analytics(){let a=await api("/analytics");shell("Аналитика","Целостная статистика по каждому аккаунту и площадке",`<div class="grid">${metric("Просмотры",a.views.toLocaleString("ru-RU"))}${metric("Лайки",a.likes.toLocaleString("ru-RU"))}${metric("Комментарии",a.comments.toLocaleString("ru-RU"))}${metric("Подписчики",a.followers.toLocaleString("ru-RU"))}</div><div class="grid2"><div class="card"><b>Площадки</b><table class="table"><tr><th>Площадка</th><th>Клипы</th><th>Просмотры</th><th>Лайки</th></tr>${a.platforms.map(x=>`<tr><td>${x.platform}</td><td>${x.clips}</td><td>${x.views.toLocaleString("ru-RU")}</td><td>${x.likes.toLocaleString("ru-RU")}</td></tr>`).join("")}</table></div><div class="card"><b>Аккаунты</b><div class="list">${a.accounts.map(x=>`<div class="item row"><span>${x.platform} · ${x.username||"—"}</span><b>${x.views.toLocaleString("ru-RU")}</b></div>`).join("")||'<div class="empty">Нет метрик</div>'}</div></div></div>`)}
function registration(){shell("Регистрация аккаунтов","Официальный workflow создания/подключения",`<div class="grid2"><div class="card"><h3>Начать</h3><p class="muted">Номер телефона используется только для запуска официального процесса площадки. CAPTCHA и обязательные проверки проходят на стороне площадки.</p><div class="form"><label>Площадка<select><option>TikTok</option><option>Instagram</option><option>YouTube</option><option>VK</option></select></label><label>Номер телефона<input placeholder="+49 ..."></label><button class="btn">Запустить официальный процесс</button></div></div><div class="card"><h3>После регистрации</h3><div class="list"><div class="item">1. Авторизовать аккаунт на физическом устройстве</div><div class="item">2. Добавить устройство в VerticalOS</div><div class="item">3. Привязать аккаунт к устройству</div><div class="item">4. Настроить контент и аналитику</div></div></div></div>`)}
function nav(){document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>{document.querySelectorAll("nav a").forEach(n=>n.classList.remove("active"));a.classList.add("active");({dashboard,content,accounts,devices,publishing,tasks,analytics,registration}[a.dataset.page]||dashboard)()})}
nav();dashboard();
