
const $=s=>document.querySelector(s), view=$("#view"), modal=$("#modal");
const telegramWebApp=window.Telegram?.WebApp; telegramWebApp?.ready(); telegramWebApp?.expand();
function authHeaders(extra={}){return {"X-Telegram-Init-Data":telegramWebApp?.initData||"",...extra}}
const localLogin=(async()=>{const token=new URLSearchParams(location.hash.slice(1)).get("localToken");if(token){history.replaceState(null,"",location.pathname);const r=await fetch("/api/local-session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});if(!r.ok)throw new Error("Не удалось открыть локальный FaxClip");}})();
async function api(path,opt={}){await localLogin;const r=await fetch("/api"+path,{...opt,headers:authHeaders({"Content-Type":"application/json",...(opt.headers||{})})});const x=await r.json();if(!r.ok)throw new Error(x.error||`HTTP ${r.status}`);return x}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function pct(a,b){return b?Math.min(100,Math.round(a/b*100)):0}
function modalBox(html){modal.innerHTML=`<div class="modalbox">${html}</div>`;modal.classList.add("show")}
function closeModal(){modal.classList.remove("show")}
modal.onclick=e=>{if(e.target===modal)closeModal()}
function shell(title,sub,html,action=""){ $("#title").textContent=title;$("#subtitle").textContent=sub;$("#headerAction").innerHTML=action;view.innerHTML=html}
function metric(l,v,s=""){return `<div class="card"><div class="label">${l}</div><div class="metric">${v}</div><div class="muted" style="margin-top:6px">${s}</div></div>`}

async function dashboard(){let d=await api("/dashboard");shell("Главная","Автоматизируй процесс!",`
<div class="grid">${metric("Аккаунты",d.accounts,"подключено")}${metric("Устройства",d.devices,"онлайн")}${metric("Клипы",d.clips,"вертикальные 9:16")}${metric("Просмотры",d.views.toLocaleString("ru-RU"),"собрано")}</div>
<div class="grid2"><div class="card"><b>Быстрые действия</b><div class="quick-actions"><button class="btn" onclick="goPage('accounts')">＋ Аккаунт</button><button class="btn" onclick="goPage('devices')">＋ Телефон</button><button class="btn secondary" onclick="goPage('content')">Загрузить видео</button><button class="btn secondary" onclick="goPage('tasks')">Создать задачу</button></div></div>
<div class="card"><div class="row"><b>Задачи</b><b>${d.task_percent}%</b></div><div class="progress"><div class="bar" style="width:${d.task_percent}%"></div></div><div class="muted">${d.task_done} / ${d.task_target}</div></div></div>
<div class="card" style="margin-top:14px"><div class="row"><b>Сводка</b><span class="pill">Данные приложения</span></div><div class="list"><div class="item">▶️ Просмотры: <b>${d.views.toLocaleString("ru-RU")}</b></div><div class="item">📤 Опубликовано клипов: <b>${d.publications}</b></div><div class="item">❤️ Лайков: <b>${d.likes.toLocaleString("ru-RU")}</b></div><div class="item">👥 Новых подписчиков: <b>${d.followers.toLocaleString("ru-RU")}</b></div></div></div>`)}
async function accounts(){let a=await api("/accounts");shell("Аккаунты","Профили, устройства и целевая аудитория",`<div class="card"><div class="row"><b>Все аккаунты</b><button class="btn" onclick="addAccount()">+ Добавить</button></div><table class="table"><thead><tr><th>Площадка</th><th>Аккаунт</th><th>Устройство</th><th>Ниша / ЦА</th><th>Статус</th><th></th></tr></thead><tbody>${a.map(x=>`<tr><td>${x.platform}</td><td><b>${esc(x.username||"Без username")}</b></td><td>${esc(x.device||"—")}</td><td>${esc(x.niche||"—")}<br><span class="muted">${esc(x.audience||"")}</span></td><td><span class="pill"><i class="dot"></i>${["CONNECTED","ADDED"].includes(x.status)?"Профиль добавлен":esc(x.status)}</span></td><td><button class="btn secondary" onclick="accountInfo()">О подключении</button></td></tr>`).join("")||`<tr><td colspan="6" class="empty">Аккаунтов пока нет</td></tr>`}</tbody></table></div>`)}
async function addAccount(){let d=await api("/devices");modalBox(`<h3>Добавить аккаунт</h3><p class="muted">Эта форма сохраняет профиль и привязку к устройству. Вход в площадку и доступ к публикации ещё не подключены.</p><div class="form"><label>Площадка<select id="ap"><option>TikTok</option><option>Instagram</option><option>YouTube</option><option>VK</option></select></label><label>Username<input id="au" placeholder="@username"></label><label>Устройство<select id="ad"><option value="">Не назначено</option>${d.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}</select></label><label>Ниша<input id="an" placeholder="Beauty / Education / Gaming"></label><label>Целевая аудитория<input id="aa" placeholder="Описание ЦА"></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveAccount()">Сохранить</button></div></div>`)}
async function saveAccount(){if(!document.getElementById("au").value.trim())throw new Error("Укажите username аккаунта");await api("/accounts",{method:"POST",body:JSON.stringify({platform:document.getElementById("ap").value,username:document.getElementById("au").value,niche:document.getElementById("an").value,audience:document.getElementById("aa").value,device_id:document.getElementById("ad").value||null})});closeModal();await accounts()}
async function devices(){let d=await api("/devices");shell("Устройства","Физические Android-смартфоны",`<div class="grid">${d.map(x=>`<div class="card"><div class="row"><b>📱 ${esc(x.name)}</b><span class="pill"><i class="dot ${x.status==="ONLINE"?"":"red"}"></i>${["CONNECTED","ADDED"].includes(x.status)?"Профиль добавлен":esc(x.status)}</span></div><div class="muted" style="margin-top:10px">${esc(x.model)}</div><div style="margin-top:12px">🔋 ${x.battery}%</div><div class="muted">Аккаунтов: ${x.accounts}</div><div class="muted">ID: ${esc(x.id)}</div><div class="muted">Ожидает ПК-мост через USB / ADB</div></div>`).join("")||`<div class="card empty">Нет устройств</div>`}</div><div class="card" style="margin-top:14px"><div class="row"><b>Подключение нового телефона</b><button class="btn" onclick="addDevice()">+ Добавить</button></div><p class="muted" style="margin-top:8px">Сохраните ID и токен устройства в локальной конфигурации ПК-моста. Телефон подключается по USB; мост сообщает заряд и получает задания.</p></div>`)}
function addDevice(){modalBox(`<h3>Добавить устройство</h3><div class="form"><label>Название<input id="dn" value="Phone #01"></label><label>Модель<input id="dm" placeholder="Samsung Galaxy / Pixel"></label><label>Канал<select id="dc"><option>USB / ADB</option><option>LAN / ADB</option></select></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveDevice()">Создать</button></div></div>`)}
async function saveDevice(){let x=await api("/devices",{method:"POST",body:JSON.stringify({name:document.getElementById("dn").value,model:document.getElementById("dm").value,connection:document.getElementById("dc").value})});closeModal();await devices();modalBox(`<h3>Устройство добавлено</h3><p>Это регистрация устройства, а не подключение телефона. Установите ПК-мост из папки bridge и подключите телефон по USB. Это не APK агента: управление выполняется на ПК через ADB.</p><p style="margin-top:16px">ID устройства: ${esc(x.id)}</p><p style="margin-top:16px">Токен показывается один раз. Сохраните его, не публикуйте:</p><p class="device-token">${esc(x.device_token)}</p><button class="btn" onclick="closeModal()">Сохранил</button>`)}
async function tasks(){let t=await api("/tasks");shell("Задачи","KPI и автоматический прогресс 0–100%",`<div class="row" style="margin-bottom:14px"><span class="muted">Прогресс может увеличиваться автоматически после успешных публикаций</span><button class="btn" onclick="addTask()">+ Новая</button></div><div class="list">${t.map(x=>{let p=pct(x.done,x.target);return `<div class="card"><div class="row"><div><b>${esc(x.title)}</b><div class="muted">${x.done} / ${x.target} ${esc(x.unit)} · ${{DAY:"День",WEEK:"Неделя",MONTH:"Месяц"}[x.period]||"День"}</div></div><b>${p}%</b></div><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="row"><span class="muted">${x.deadline||"Без дедлайна"}</span><button class="btn secondary" onclick="editTask('${x.id}',${x.done},${x.target})">Изменить</button></div></div>`}).join("")||`<div class="card empty">Нет задач</div>`}</div>`)}
function addTask(){modalBox(`<h3>Новая задача</h3><div class="form"><label>Название<input id="tt" placeholder="Опубликовать 100 клипов"></label><div class="formgrid"><label>Цель<input id="tg" type="number" value="100"></label><label>Единица<input id="tu" value="клипов"></label></div><label>Период<select id="tp"><option value="DAY">День</option><option value="WEEK">Неделя</option><option value="MONTH">Месяц</option></select></label><label>Дедлайн<input id="td" type="date"></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveTask()">Создать</button></div></div>`)}
async function saveTask(){if(!document.getElementById("tt").value.trim())throw new Error("Укажите название задачи");await api("/tasks",{method:"POST",body:JSON.stringify({title:document.getElementById("tt").value,target:+document.getElementById("tg").value,unit:document.getElementById("tu").value,deadline:document.getElementById("td").value,period:document.getElementById("tp").value})});closeModal();await tasks()}
function editTask(id,done,target){modalBox(`<h3>Прогресс задачи</h3><div class="form"><label>Выполнено<input id="ed" type="number" min="0" max="${target}" value="${done}"></label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveTaskProgress('${id}')">Сохранить</button></div></div>`)}
async function saveTaskProgress(id){await api(`/tasks/${id}`,{method:"PATCH",body:JSON.stringify({done:+document.getElementById("ed").value})});closeModal();await tasks()}
async function content(){let c=await api("/clips");shell("Контент","Только вертикальные клипы 9:16",`<div class="card"><div class="row"><b>Клипы</b><button class="btn" onclick="addClip()">+ Загрузить</button></div><table class="table"><thead><tr><th>Название</th><th>Длительность</th><th>AI Score</th><th>Статус</th></tr></thead><tbody>${c.map(x=>`<tr><td>${esc(x.title)}</td><td>${Math.round(x.duration)} сек.</td><td>${x.score}/100</td><td><span class="pill">${["CONNECTED","ADDED"].includes(x.status)?"Профиль добавлен":esc(x.status)}</span></td></tr>`).join("")||`<tr><td colspan="4" class="empty">Клипов нет</td></tr>`}</tbody></table></div><div class="card" style="margin-top:14px"><b>Работа с видео</b><div class="list"><div class="item">Загрузка видео и сохранение карточки клипа</div><div class="item">Добавление клипа в очередь заданий</div><div class="item">Описание сохраняется с клипом. В разделе «Публикации» поставьте его в очередь для @redmaagi. AI-нарезка, баннеры и автоматический сбор статистики пока не подключены.</div></div></div>`)}
function addClip(){modalBox(`<h3>Добавить вертикальное видео</h3><div class="form"><label>Видео<input id="cf" type="file" accept="video/*"></label><label>Название<input id="ct" value="Новый ролик"></label><label>Описание для TikTok<textarea id="cc" maxlength="2200" rows="4" placeholder="Текст будет введён без изменений"></textarea></label><div class="formgrid"><label>Длительность, если известна<input id="cd" type="number" min="0" value="0"></label></div><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="saveClip()">Загрузить</button></div></div>`)}
async function saveClip(){await localLogin;let source_file=null;if(!document.getElementById("cf").files[0])throw new Error("Выберите видеофайл");if(document.getElementById("cf").files[0]){let fd=new FormData();fd.append("file",document.getElementById("cf").files[0]);let r=await fetch("/api/media/upload",{method:"POST",headers:authHeaders(),body:fd});let x=await r.json();if(!r.ok)throw new Error(x.error||"Upload failed");source_file=x.filename}await api("/clips",{method:"POST",body:JSON.stringify({title:document.getElementById("ct").value,duration:+document.getElementById("cd").value,score:0,source_file,caption:document.getElementById("cc").value})});closeModal();await content()}
function publicationStatus(x){return ({QUEUED:"В очереди",RUNNING:"Телефон выполняет",UI_CONFIRMED:"Пост подтверждён в TikTok",NEEDS_REVIEW:"Нужна проверка; очередь остановлена",TRANSFERRED_NEEDS_AUTOMATION:"Старая подготовка, без публикации"})[x.status]||x.status;}
function postLink(url){return typeof url==="string"&&/^https:\/\/www\.tiktok\.com\/@redmaagi\/video\/[0-9]{10,25}$/.test(url)?` <a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Открыть пост</a>`:"";}
async function publishing(){let p=await api("/publications");shell("Публикации","Очередь и история",`<div class="row" style="margin-bottom:14px"><span class="muted">TikTok @redmaagi: видео и описание из FaxClip → подключённый телефон → отправка → проверка профиля и ссылки. Неопределённый результат останавливает очередь без повтора. На текущем бесплатном Render файлы и очередь не являются постоянным архивом: после перезапуска сервера они могут пропасть.</span><div class="row"><button class="btn secondary" onclick="connectMac()">Подключить Mac</button><button class="btn" onclick="uploadAndPublish()">Загрузить и опубликовать</button><button class="btn secondary" onclick="addPublication()">Клип из библиотеки</button></div></div><div class="card"><table class="table"><thead><tr><th>Клип</th><th>Аккаунт</th><th>Площадка</th><th>Статус</th><th>Отчёт</th></tr></thead><tbody>${p.map(x=>`<tr><td>${esc(x.clip)}</td><td>${esc(x.account)}</td><td>${esc(x.platform)}</td><td><span class="pill">${esc(publicationStatus(x))}</span></td><td><button class="btn secondary" onclick="showEvidence('${x.id}')">Скриншот</button>${postLink(x.external_id)}<div class="muted">${esc(x.error||"")}</div></td></tr>`).join("")||`<tr><td colspan="5" class="empty">Очередь пуста</td></tr>`}</tbody></table></div>`)}
let publicationKey=null,publicationClips=[];
function fillPublicationCaption(){const clip=publicationClips.find(x=>x.id===document.getElementById("pc").value);document.getElementById("postCaption").value=clip?.caption||"";}
async function addPublication(){
 const [clips,accounts]=await Promise.all([api("/clips"),api("/accounts")]);
 const ready=accounts.filter(x=>x.device_id&&x.platform==="TikTok"&&x.username==="@redmaagi");
 if(!clips.length||!ready.length){modalBox('<h3>Подготовка публикации</h3><p>Загрузите MP4-видео, добавьте аккаунт с точным username и назначьте телефон. Для исполнения нужен включённый мост FaxClip v14 и подключённый Redmi.</p><button class="btn" style="margin-top:16px" onclick="closeModal()">Понятно</button>');return}
 publicationKey=crypto.randomUUID();publicationClips=clips;
 modalBox(`<h3>Публикация через телефон</h3><div class="form"><label>Клип<select id="pc" onchange="fillPublicationCaption()">${clips.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("")}</select></label><label>Аккаунт<select id="pa">${ready.map(x=>`<option value="${x.id}">${esc(x.platform)} · ${esc(x.username)}</option>`).join("")}</select></label><label>Заголовок<input id="postTitle" maxlength="100"></label><label>Описание<textarea id="postCaption" maxlength="2200" rows="4"></textarea></label><label>Дата и время на вашем устройстве<input id="ps" type="datetime-local"></label><p>РЕАЛЬНАЯ публикация для всех на @redmaagi. Нужны включённый мост FaxClip на Mac, USB и служба помощника v14. Остальные площадки в этой сборке отключены.</p><label><input id="postConsent" type="checkbox"> Подтверждаю публичную публикацию этого видео на выбранном аккаунте</label><label><input id="rightsConsent" type="checkbox"> Подтверждаю права на видео и использование музыки; разрешаю принять соответствующее подтверждение TikTok</label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" id="postSubmit" onclick="savePublication()">В очередь</button></div></div>`);fillPublicationCaption();
}
async function savePublication(){
 const button=document.getElementById("postSubmit");if(button.disabled)return;
 if(!document.getElementById("postConsent").checked){showAppError(new Error("Подтвердите публикацию галочкой"));return}
 if(!document.getElementById("rightsConsent").checked){showAppError(new Error("Подтвердите права на видео и музыку"));return}
 if(!document.getElementById("postCaption").value.trim()){showAppError(new Error("Добавьте описание"));return}
 button.disabled=true;
 try{const date=document.getElementById("ps").value;
 await api("/publications",{method:"POST",headers:{"Idempotency-Key":publicationKey},body:JSON.stringify({clip_id:document.getElementById("pc").value,account_id:document.getElementById("pa").value,title:document.getElementById("postTitle").value,caption:document.getElementById("postCaption").value,scheduled_at:date?new Date(date).toISOString():null,confirmed:true,rights_confirmed:true})});closeModal();await publishing()
 }catch(e){showAppError(e)}finally{button.disabled=false}
}
async function analytics(){let a=await api("/analytics");shell("Аналитика","Целостная статистика по каждому аккаунту и площадке",`<div class="grid">${metric("Просмотры",a.views.toLocaleString("ru-RU"))}${metric("Лайки",a.likes.toLocaleString("ru-RU"))}${metric("Комментарии",a.comments.toLocaleString("ru-RU"))}${metric("Подписчики",a.followers.toLocaleString("ru-RU"))}</div><div class="grid2"><div class="card"><b>Площадки</b><table class="table"><tr><th>Площадка</th><th>Клипы</th><th>Просмотры</th><th>Лайки</th></tr>${a.platforms.map(x=>`<tr><td>${x.platform}</td><td>${x.clips}</td><td>${x.views.toLocaleString("ru-RU")}</td><td>${x.likes.toLocaleString("ru-RU")}</td></tr>`).join("")}</table></div><div class="card"><b>Аккаунты</b><div class="list">${a.accounts.map(x=>`<div class="item row"><span>${x.platform} · ${x.username||"—"}</span><b>${x.views.toLocaleString("ru-RU")}</b></div>`).join("")||'<div class="empty">Нет метрик</div>'}</div></div></div>`)}
const routes={dashboard,content,accounts,devices,publishing,tasks,analytics,registration};
let navigationId=0;
async function goPage(name){
 const current=++navigationId;
 document.querySelectorAll("nav .nav-item").forEach(n=>{n.classList.toggle("active",n.dataset.page===name);n.setAttribute("aria-current",n.dataset.page===name?"page":"false")});
 document.getElementById("appError")?.remove();
 view.innerHTML='<div class="card" role="status">Загрузка…</div>';
 try{await (routes[name]||dashboard)();}catch(e){if(current===navigationId){view.innerHTML='<div class="card">Не удалось загрузить раздел. Причина указана выше.</div>';showAppError(e)}}
}
function nav(){document.querySelectorAll("nav .nav-item").forEach(a=>a.onclick=()=>goPage(a.dataset.page))}
function accountInfo(){modalBox('<h3>Подключение аккаунта</h3><p>Профиль сохранён в FaxClip. Это ещё не авторизация на площадке. Для @redmaagi привяжите проверенный Redmi и включите мост v14. Другие профили пока не поддерживаются этим маршрутом. Для публикации API площадок не используется. Сбор статистики с площадок пока не реализован.</p><button class="btn" style="margin-top:16px" onclick="closeModal()">Понятно</button>')}
function registration(){shell("Регистрация","Добавление профиля в FaxClip",'<div class="card"><h3>Добавить существующий аккаунт</h3><p>FaxClip сохраняет профиль, нишу, целевую аудиторию и связь с устройством. Войдите в аккаунты вручную на телефоне. Пароли площадок FaxClip не хранит; публикацию выполняет ПК-мост.</p><button class="btn" style="margin-top:16px" onclick="addAccount()">Добавить аккаунт</button></div>')}
const tableObserver=new MutationObserver(()=>{document.querySelectorAll("#view table.table").forEach(t=>{if(!t.parentElement.classList.contains("table-wrap")){const w=document.createElement("div");w.className="table-wrap";t.parentNode.insertBefore(w,t);w.append(t)}})});tableObserver.observe(view,{childList:true,subtree:true});
function showAppError(error){
 const message=error?.message||String(error||"Неизвестная ошибка");
 const translations={
  "Telegram authorization is required":"Откройте приложение через кнопку меню бота в Telegram. При открытии обычной ссылки данные входа не передаются.",
  "Invalid Telegram signature":"Подпись Telegram не совпала. Проверьте, что TELEGRAM_BOT_TOKEN в Render принадлежит именно боту, через которого открыто приложение. После смены токена перезапустите сервис и заново откройте Mini App.",
  "Telegram authorization expired":"Сессия истекла. Полностью закройте Mini App и откройте её снова через кнопку бота.",
  "Telegram user is not allowed":"Ваш Telegram ID отсутствует в списке разрешённых пользователей."
 };
 let box=document.getElementById("appError");
 if(!box){box=document.createElement("div");box.id="appError";box.setAttribute("role","alert");box.style.cssText="background:#3b1820;color:#fff;padding:16px;margin:12px;border-radius:12px;position:relative;z-index:10000;white-space:pre-wrap";document.querySelector("main").prepend(box)}
 box.replaceChildren();const text=document.createElement("p");text.textContent=translations[message]||message;box.append(text);
 const detail=document.createElement("small");detail.textContent="Telegram: "+(telegramWebApp?.initData?"данные входа получены":"данные входа отсутствуют")+" · Ошибка: "+message;box.append(detail);
 const retry=document.createElement("button");retry.className="btn";retry.style.marginLeft="12px";retry.textContent="Повторить";retry.onclick=()=>{box.remove();const name=document.querySelector("nav .nav-item.active")?.dataset.page||"dashboard";Promise.resolve(({dashboard,content,accounts,devices,publishing,tasks,analytics,registration}[name])()).catch(showAppError)};box.append(retry);
}
window.addEventListener("unhandledrejection",e=>{e.preventDefault();showAppError(e.reason)});
window.addEventListener("error",e=>{showAppError(e.error||e.message)});
nav();goPage("dashboard");

let evidenceUrl=null;
async function showEvidence(id){
 try{const r=await fetch(`/api/publications/${id}/evidence`,{headers:authHeaders()});if(!r.ok)throw new Error("Скриншот пока недоступен");if(evidenceUrl)URL.revokeObjectURL(evidenceUrl);evidenceUrl=URL.createObjectURL(await r.blob());modalBox(`<h3>Отчёт с телефона</h3><p>Подтверждение по интерфейсу, не проверка через API площадки.</p><img style="display:block;max-width:100%;margin:16px auto" src="${evidenceUrl}" alt="Экран телефона после задания"><button class="btn" onclick="closeModal()">Закрыть</button>`)}catch(e){showAppError(e)}
}

setInterval(()=>{if(!document.hidden&&!modal.classList.contains("show")&&document.querySelector("nav .nav-item.active")?.dataset.page==="publishing")publishing().catch(showAppError)},7000);
let directUpload=null;
async function uploadAndPublish(){
 const accounts=(await api('/accounts')).filter(x=>x.platform==='TikTok'&&x.username==='@redmaagi'&&x.device_id);
 if(!accounts.length)throw new Error('Сначала подключите проверенный Redmi к аккаунту @redmaagi');
 directUpload={key:crypto.randomUUID(),clipId:null};
 modalBox(`<h3>Загрузить и опубликовать</h3><div class="form"><label>MP4-видео<input id="directFile" type="file" accept="video/mp4,.mp4" onchange="directUpload={key:crypto.randomUUID(),clipId:null}"></label><label>Описание<textarea id="directCaption" maxlength="2200" rows="4" placeholder="Текст для TikTok"></textarea></label><label>Аккаунт<select id="directAccount">${accounts.map(a=>`<option value="${a.id}">${esc(a.username)} · TikTok</option>`).join('')}</select></label><p>После подтверждения FaxClip возьмёт видео и описание из очереди. Mac должен работать, а телефон — быть подключён и разблокирован. Публикация публичная.</p><label><input id="directConsent" type="checkbox"> Разрешаю опубликовать этот ролик на выбранном аккаунте</label><label><input id="directRights" type="checkbox"> Подтверждаю права на видео и музыку, разрешаю принять подтверждение TikTok</label><div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" id="directSubmit" onclick="saveDirectPublication()">Загрузить и отправить</button></div></div>`);
}
async function saveDirectPublication(){
 const button=document.getElementById('directSubmit');if(button.disabled)return;
 const state=directUpload,file=document.getElementById('directFile').files[0],caption=document.getElementById('directCaption').value,accountId=document.getElementById('directAccount').value;
 if(!file||!caption.trim())throw new Error('Выберите MP4 и добавьте описание');
 if(!document.getElementById('directConsent').checked||!document.getElementById('directRights').checked)throw new Error('Подтвердите публикацию и права');
 button.disabled=true;
 const controls=[...document.querySelectorAll('#directFile,#directCaption,#directAccount,#directConsent,#directRights')];controls.forEach(x=>x.disabled=true);
 try{
  if(!state.clipId){
   await localLogin;const form=new FormData();form.append('file',file);
   const r=await fetch('/api/media/upload',{method:'POST',headers:authHeaders(),body:form});const media=await r.json();if(!r.ok)throw new Error(media.error||'Загрузка не завершена');
   const clip=await api('/clips',{method:'POST',body:JSON.stringify({title:file.name,source_file:media.filename,duration:0,score:0,caption})});state.clipId=clip.id;
  }
  if(directUpload!==state||!button.isConnected||!modal.classList.contains('show'))return;
  await api('/publications',{method:'POST',headers:{'Idempotency-Key':state.key},body:JSON.stringify({clip_id:state.clipId,account_id:accountId,caption,confirmed:true,rights_confirmed:true})});
  closeModal();await publishing();
 }catch(e){showAppError(e)}finally{button.disabled=false;controls.forEach(x=>{if(x.isConnected)x.disabled=false})}
}

async function connectMac(){
 const r=await api('/phone-pairing',{method:'POST',body:'{}'});
 modalBox(`<h3>Подключить Mac к Telegram FaxClip</h3><p><a href="https://github.com/ncappp/verticalos/releases/download/faxclip-v14-telegram/faxclip-telegram-bridge-v14.zip" target="_blank" rel="noopener noreferrer">Скачать мост для Mac и APK v14</a></p><p>Запустите 02-connect-telegram-faxclip.command на Mac с подключённым Redmi и введите этот одноразовый код в его терминале:</p><p style="font-size:24px;letter-spacing:2px;margin:20px 0"><b>${esc(r.code)}</b></p><p>Код действует 10 минут и привязан к @redmaagi. Не отправляйте его в чат и не публикуйте. При повторном подключении старый мост потеряет доступ.</p><p>После подключения загрузка видео и описания выполняется здесь, в Telegram. Mac должен оставаться включён.</p><button class="btn" style="margin-top:16px" onclick="closeModal();devices()">Готово</button>`);
}
