/* FaxClip «Склейка»: recipes, render jobs on the Mac, sources with daily ramp-up. */
(function(){
const JST={queued:["В очереди",""],running:["Mac склеивает",""],done:["Готово",""],failed:["Ошибка","red"],canceled:["Отменено","red"]};
const FONTS=["Arial Bold","Arial","Helvetica","Impact","Georgia","Verdana Bold","Trebuchet MS Bold","Courier New Bold"];
const A={tab:"recipes"};
const fmt=t=>t?new Date(typeof t==="number"?t*1000:t).toLocaleString("ru-RU",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"—";
const pill=(m,s)=>{const [l,c]=m[s]||[s,""];return `<span class="pill"><i class="dot ${c}"></i>${l}</span>`};
const v=id=>{const e=document.getElementById(id);return e?(e.type==="checkbox"?e.checked:e.value.trim()):""};
const errBox='<p id="wsErr" class="ws-err" style="display:none"></p>';
const fail=e=>{const b=document.getElementById("wsErr");if(b){b.textContent=e.message||String(e);b.style.display="block"}else showAppError(e)};
const opt=(val,l,cur)=>`<option value="${esc(val)}" ${String(val)===String(cur)?"selected":""}>${esc(l)}</option>`;
async function page(){
 const [rs,jobs,src,acc]=await Promise.all([api("/recipes"),api("/render-jobs"),api("/sources"),api("/accounts")]);
 const agent=jobs.agent_online?`<span class="pill"><i class="dot"></i>Mac на связи</span>`:`<span class="pill"><i class="dot red"></i>Mac склейки не на связи</span>`;
 const tabs=[["recipes","Рецепты "+rs.length],["jobs","Задачи "+jobs.items.length],["sources","Источники "+src.length]];
 let html="";
 if(A.tab==="recipes")html=`<div class="list">${rs.map(r=>`<div class="item row ws-post"><div style="flex:1;min-width:0"><b>${esc(r.name)}</b> ${r.enabled?'<span class="pill"><i class="dot"></i>Включён</span>':'<span class="pill"><i class="dot red"></i>Выключен</span>'}
  <div class="muted">${r.source_type==="yandex"?"Яндекс.Диск":"Mac: Загрузки/"+esc(r.source_url)} · сцен: ${(r.scenes||[]).length} · текстов: ${r.texts_count} · ${r.period_hours?"каждые "+r.period_hours+" ч, следующий "+fmt(r.next_run_at):"только вручную"}</div>
  <div class="muted">${r.auto_publish?`Автопубликация · аккаунтов: ${r.sources}`:"Без автопубликации — ролики попадут в «Контент»"}${r.last?` · последний: ${r.last.status==="done"?"готов":"ошибка"} ${fmt(r.last.finished_at)}`:""}</div></div>
  <div class="row" style="gap:6px;flex-wrap:wrap;justify-content:flex-end"><button class="btn secondary" onclick="asScan('${r.id}',this)">Проверить папки</button><button class="btn secondary" onclick="asForm('${r.id}')">Изменить</button><button class="btn" onclick="asRun('${r.id}')">Собрать</button></div></div>`).join("")||'<div class="empty">Рецептов пока нет. Рецепт — это порядок сцен: в каждой папке лежат дубли, Mac берёт случайный.</div>'}</div>`;
 if(A.tab==="jobs")html=`<table class="table"><thead><tr><th>Ролик</th><th>Статус</th><th>Аккаунт</th><th>Файлы</th><th></th></tr></thead><tbody>${jobs.items.map(j=>`<tr><td><b>${esc(j.title||j.recipe||"—")}</b><br><span class="muted">${esc(j.recipe||"")} · ${fmt(j.created_at)}</span></td><td>${pill(JST,j.status)}${j.duration?`<div class="muted">${j.duration} сек.</div>`:""}</td><td>${esc(j.username||"—")}${j.post_id?'<div class="muted">отправлен в «Посты»</div>':""}</td><td class="muted">${(j.files||[]).map(esc).join("<br>")||"—"}${j.error?`<div style="color:#ff8a8a">${esc(j.error)}</div>`:""}</td><td>${["failed","canceled"].includes(j.status)?`<button class="btn secondary" onclick="asJob('${j.id}','retry')">Повторить</button>`:""}${j.status==="queued"?`<button class="btn secondary" onclick="asJob('${j.id}','cancel')">Отменить</button>`:""}</td></tr>`).join("")||'<tr><td colspan="5" class="empty">Задач пока нет</td></tr>'}</tbody></table>`;
 if(A.tab==="sources")html=`<p class="muted">Источник — какой аккаунт получает ролики из какого рецепта. Вес делит ролики между аккаунтами. Наращивание: в первый день «старт» роликов, затем каждый день больше, пока не дойдёт до «цели».</p>
  <table class="table"><thead><tr><th>Аккаунт</th><th>Рецепт</th><th>Вес</th><th>Сегодня</th><th>Наращивание</th><th>Активен</th><th></th></tr></thead><tbody>${src.map(s=>`<tr><td><b>${esc(s.username||"—")}</b><br><span class="muted">${esc(s.platform||"")}</span></td><td>${esc(s.recipe||"—")}</td><td>${s.weight}</td><td>${s.today} из ${s.quota}</td><td class="muted">${s.start_per_day} → ${s.target_per_day} в день за ${s.ramp_days} дн.</td><td>${s.active?"Да":"Нет"}</td><td><button class="btn secondary" onclick="asSrcForm('${s.id}')">Изменить</button> <button class="btn secondary" onclick="asSrcDel('${s.id}')">Удалить</button></td></tr>`).join("")||'<tr><td colspan="7" class="empty">Источников пока нет</td></tr>'}</tbody></table>`;
 const action=A.tab==="sources"?`<button class="btn" onclick="asSrcForm()">+ Источник</button>`:`<button class="btn" onclick="asForm()">+ Рецепт</button>`;
 shell("Склейка","Автомонтаж роликов из ваших дублей",`<div class="row" style="flex-wrap:wrap;gap:10px;margin-bottom:12px"><div class="tabs ws-tabs" style="margin:0">${tabs.map(([k,l])=>`<button class="${A.tab===k?"active":""}" onclick="asTab('${k}')">${l}</button>`).join("")}</div><div class="row" style="gap:8px">${agent}<button class="btn secondary" onclick="asInstall()">Установить склейку на Mac</button></div></div>
 <div class="card ws-posts">${html}</div>`,action)}
window.asTab=t=>{A.tab=t;page().catch(showAppError)};
window.asJob=async(id,a)=>{try{await api(`/render-jobs/${id}/${a}`,{method:"POST",body:"{}"});await page()}catch(e){showAppError(e)}};
window.asRun=id=>modalBox(`<h3>Собрать ролики</h3><div class="form"><label>Сколько роликов<input id="asN" type="number" min="1" max="20" value="1"></label><p class="muted">Mac склеит ролики по очереди. Если включена автопубликация, ролики уйдут на аккаунты из «Источников».</p>${errBox}<div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="asRunGo('${id}')">Собрать</button></div></div>`);
window.asRunGo=async id=>{try{const r=await api(`/recipes/${id}/run`,{method:"POST",body:JSON.stringify({count:+v("asN")||1})});closeModal();A.tab="jobs";await page();const j=await api("/render-jobs");if(!j.agent_online)modalBox(`<h3>Задачи созданы: ${r.jobs.length}</h3><p>Mac склейки сейчас не на связи. Нажмите «Установить склейку на Mac» — после установки ролики начнут собираться сами.</p><div class="row"><button class="btn" onclick="closeModal()">Понятно</button></div>`)}catch(e){fail(e)}};
window.asScan=async(id,btn)=>{btn.disabled=true;btn.textContent="Проверяю…";try{let s=await api(`/recipes/${id}/scan`,{method:"POST",body:"{}"});
 for(let i=0;s.pending&&i<20;i++){await new Promise(r=>setTimeout(r,3000));const r=await api("/recipes/"+id);s=r.scan||{}}
 if(s.pending){modalBox(`<h3>Ждём Mac</h3><p>Папки на Mac проверяет программа склейки. Похоже, она не запущена — нажмите «Установить склейку на Mac».</p><div class="row"><button class="btn" onclick="closeModal()">Понятно</button></div>`);return}
 const items=(s.items||[]).filter(i=>i.path!=="/"),root=(s.items||[]).find(i=>i.path==="/");
 modalBox(`<h3>${s.ok?"Папки в порядке":"Есть проблемы"}</h3>${s.error?`<p class="ws-err" style="display:block">${esc(s.error)}</p>`:""}${root?`<p class="muted">В корне: ${root.folders.map(esc).join(", ")||"пусто"}</p>`:""}<table class="table"><tbody>${items.map(i=>`<tr><td><b>${esc(i.path)}</b></td><td>${i.error?`<span style="color:#ff8a8a">${esc(i.error)}</span>`:`видео: ${i.videos} · аудио: ${i.audio}`}</td></tr>`).join("")}</tbody></table><div class="row"><button class="btn" onclick="closeModal()">Понятно</button></div>`)}catch(e){showAppError(e)}finally{btn.disabled=false;btn.textContent="Проверить папки"}};
window.asInstall=async()=>{let cmd="";try{cmd=(await api("/render-install-command")).command}catch(e){}
 modalBox(`<h3>Склейка на Mac</h3><p>Ролики собирает ваш Mac (бесплатный сервер не тянет монтаж). Откройте «Терминал» на Mac, вставьте команду и нажмите Enter. Установка займёт 1–3 минуты.</p>${cmd?`<textarea readonly rows="5" style="width:100%;font-family:monospace;font-size:12px" onclick="this.select()">${esc(cmd)}</textarea><div class="row"><button class="btn secondary" onclick="navigator.clipboard.writeText(document.querySelector('#modal textarea, .modal textarea').value).then(()=>this.textContent='Скопировано')">Скопировать</button><button class="btn" onclick="closeModal()">Готово</button></div>`:'<p class="ws-err" style="display:block">Команда пока недоступна.</p>'}
 <p class="muted">Папки со сценами кладите в «Загрузки» на Mac, например «Загрузки/FaxClip/Склейка/intro», «…/main». Либо используйте публичную папку Яндекс.Диска.</p>`)};
/* ---------- recipe form ---------- */
let cur=null;
window.asForm=async function(id){const r=id?await api("/recipes/"+id):{name:"",enabled:false,source_type:"local",source_url:"FaxClip/Склейка",scenes:[{folder:"intro",max_sec:3},{folder:"main",max_sec:0},{folder:"outro",max_sec:3}],text_style:{},plate:{},audio:{},timing:{},text_mode:"sequential",period_hours:0,auto_publish:false,caption_template:"",texts:[]};cur=r;
 const t={font:"Arial Bold",size:64,color:"#FFFFFF",stroke_color:"#000000",stroke_width:3,line_spacing:1.15,max_lines:4,align:"center",...r.text_style};
 const p={enabled:true,color:"#000000",opacity:55,position:"center",offset:0,padding:36,radius:28,...r.plate};
 const a={original:true,original_volume:100,music_folder:"",music_volume:35,...r.audio};const tm={text_start:0,text_end:0,max_total:60,...r.timing};
 const sec=(k,l)=>`<button type="button" class="${k==="main"?"active":""}" data-as="${k}" onclick="asSec('${k}')">${l}</button>`;
 modalBox(`<h3>${id?"Рецепт склейки":"Новый рецепт"}</h3><div class="tabs ws-tabs">${sec("main","Основные")}${sec("text","Текст")}${sec("plate","Плашка")}${sec("audio","Аудио")}${sec("timing","Тайминг")}${sec("texts","Тексты")}</div><div class="form">
 <div data-sec="main"><label>Название<input id="rN" value="${esc(r.name)}" placeholder="Обзоры авто"></label>
  <div class="formgrid"><label>Где лежат дубли<select id="rST" onchange="asSrcHint()">${opt("local","Папка на Mac",r.source_type)}${opt("yandex","Яндекс.Диск (публичная ссылка)",r.source_type)}</select></label><label id="rSUl">Путь<input id="rSU" value="${esc(r.source_url||"")}"></label></div><p class="muted" id="rSH"></p>
  <b>Сцены по порядку</b><p class="muted">Одна строка — одна сцена: имя папки и максимум секунд (0 — целиком). В каждой папке 3–5 дублей, Mac берёт случайный.</p><textarea id="rSc" rows="5" placeholder="intro 3&#10;main 0&#10;outro 3">${esc((r.scenes||[]).map(s=>s.folder+" "+(s.max_sec||0)).join("\n"))}</textarea>
  <p class="muted">Размер ролика: 1080×1920 (вертикальный), 30 кадров/с.</p>
  <div class="formgrid"><label>Автозапуск<select id="rP">${opt(0,"Только вручную",r.period_hours)}${[1,2,3,4,6,8,12,24].map(h=>opt(h,"Каждые "+h+" ч",r.period_hours)).join("")}</select></label><label class="ws-check" style="margin-top:28px"><input id="rE" type="checkbox" ${r.enabled?"checked":""}> Рецепт включён</label></div>
  <label class="ws-check"><input id="rAP" type="checkbox" ${r.auto_publish?"checked":""}> Автопубликация: готовый ролик сразу уходит на аккаунт из «Источников»</label>
  <label class="ws-check"><input id="rR" type="checkbox" ${r.rights_confirmed?"checked":""}> Подтверждаю права на видео и музыку в этих папках</label>
  <label>Описание по умолчанию (если в таблице текстов нет описания)<textarea id="rCap" rows="2" maxlength="2200">${esc(r.caption_template||"")}</textarea></label></div>
 <div data-sec="text" style="display:none"><div class="formgrid"><label>Шрифт<select id="tF">${FONTS.map(f=>opt(f,f,t.font)).join("")}</select></label><label>Размер<input id="tS" type="number" min="20" max="160" value="${t.size}"></label></div>
  <div class="formgrid"><label>Цвет текста<input id="tC" type="color" value="${t.color}"></label><label>Цвет обводки<input id="tSC" type="color" value="${t.stroke_color}"></label></div>
  <div class="formgrid"><label>Толщина обводки<input id="tSW" type="number" min="0" max="12" value="${t.stroke_width}"></label><label>Межстрочный<input id="tLS" type="number" step="0.05" min="0.8" max="2.5" value="${t.line_spacing}"></label></div>
  <div class="formgrid"><label>Макс. строк<input id="tML" type="number" min="1" max="10" value="${t.max_lines}"></label><label>Выравнивание<select id="tA">${opt("left","Слева",t.align)}${opt("center","По центру",t.align)}${opt("right","Справа",t.align)}</select></label></div></div>
 <div data-sec="plate" style="display:none"><label class="ws-check"><input id="pE" type="checkbox" ${p.enabled?"checked":""}> Плашка под текстом</label>
  <div class="formgrid"><label>Цвет плашки<input id="pC" type="color" value="${p.color}"></label><label>Прозрачность, %<input id="pO" type="number" min="0" max="100" value="${p.opacity}"></label></div>
  <div class="formgrid"><label>Позиция<select id="pP">${opt("top","Сверху",p.position)}${opt("center","По центру",p.position)}${opt("bottom","Снизу",p.position)}</select></label><label>Сдвиг, % высоты<input id="pOf" type="number" min="-40" max="40" value="${p.offset}"></label></div>
  <div class="formgrid"><label>Отступ внутри<input id="pPd" type="number" min="0" max="120" value="${p.padding}"></label><label>Скругление<input id="pR" type="number" min="0" max="80" value="${p.radius}"></label></div></div>
 <div data-sec="audio" style="display:none"><label class="ws-check"><input id="aO" type="checkbox" ${a.original?"checked":""}> Оставить звук из дублей</label>
  <div class="formgrid"><label>Громкость оригинала, %<input id="aOV" type="number" min="0" max="200" value="${a.original_volume}"></label><label>Громкость музыки, %<input id="aMV" type="number" min="0" max="200" value="${a.music_volume}"></label></div>
  <label>Папка с музыкой (необязательно)<input id="aM" value="${esc(a.music_folder||"")}" placeholder="music"></label><p class="muted">Из папки берётся случайный трек (mp3, m4a, wav). Озвучка и субтитры по голосу появятся вместе с ИИ.</p></div>
 <div data-sec="timing" style="display:none"><div class="formgrid"><label>Текст появляется на секунде<input id="mS" type="number" step="0.5" min="0" value="${tm.text_start}"></label><label>Исчезает на секунде (0 — до конца)<input id="mE" type="number" step="0.5" min="0" value="${tm.text_end}"></label></div>
  <label>Максимальная длина ролика, сек.<input id="mT" type="number" min="3" max="600" value="${tm.max_total}"></label></div>
 <div data-sec="texts" style="display:none"><p class="muted">Таблица: столбец A — текст на видео, B — заголовок, C — описание с хэштегами. Можно загрузить Excel/CSV или вставить строки ниже (разделитель — «|»).</p>
  <div class="formgrid"><label>Порядок<select id="xM">${opt("sequential","По порядку",r.text_mode)}${opt("random","Случайно",r.text_mode)}</select></label><label>Позиция<input disabled value="${id?((r.text_pos||0)%Math.max(1,r.texts_count))+1+" из "+r.texts_count:"—"}"></label></div>
  ${id?`<label>Файл Excel / CSV<input id="xF" type="file" accept=".xlsx,.csv,.txt"></label><div class="row" style="justify-content:flex-start;gap:8px"><button class="btn secondary" onclick="asTextsUpload('${id}')">Загрузить файл</button><button class="btn secondary" onclick="asTextsReset('${id}')">Сбросить позицию</button></div>`:'<p class="muted">Excel можно загрузить после сохранения рецепта.</p>'}
  <label>Строки (текст | заголовок | описание)<textarea id="xT" rows="7">${esc((r.texts||[]).map(x=>[x.text,x.title,x.description].filter((s,i)=>s||i===0).join(" | ")).join("\n"))}</textarea></label></div>
 ${errBox}<div class="row" style="flex-wrap:wrap;gap:8px">${id?`<button class="btn secondary" onclick="asDel('${id}')">Удалить</button>`:""}<button class="close" onclick="closeModal()">Отмена</button><button class="btn" id="rSave" onclick="asSave('${id||""}')">Сохранить</button></div></div>`);asSrcHint()};
window.asSec=k=>{document.querySelectorAll("[data-sec]").forEach(e=>e.style.display=e.dataset.sec===k?"":"none");document.querySelectorAll("[data-as]").forEach(b=>b.classList.toggle("active",b.dataset.as===k))};
window.asSrcHint=()=>{const y=v("rST")==="yandex";document.getElementById("rSH").textContent=y?"Откройте папку на Яндекс.Диске → «Поделиться» → скопируйте ссылку. Внутри — подпапки сцен.":"Путь внутри папки «Загрузки» на Mac, например FaxClip/Склейка. Внутри — подпапки сцен.";const i=document.getElementById("rSU");i.placeholder=y?"https://disk.yandex.ru/d/…":"FaxClip/Склейка";if(y&&!/^https/.test(i.value))i.value="";if(!y&&/^https/.test(i.value))i.value="FaxClip/Склейка"};
const parseRows=s=>s.split("\n").map(l=>l.split("|").map(x=>x.trim())).filter(r=>r[0]);
window.asSave=async function(id){const btn=document.getElementById("rSave");if(btn.disabled)return;btn.disabled=true;
 try{const scenes=v("rSc").split("\n").map(l=>l.trim()).filter(Boolean).map(l=>{const m=l.match(/^(.*?)(?:\s+(\d+(?:[.,]\d+)?))?$/);return {folder:m[1].trim(),max_sec:m[2]?+m[2].replace(",","."):0}});
 const b={name:v("rN"),source_type:v("rST"),source_url:v("rSU"),scenes,period_hours:+v("rP"),enabled:v("rE"),auto_publish:v("rAP"),rights_confirmed:v("rR"),caption_template:document.getElementById("rCap").value,text_mode:v("xM"),
  text_style:{font:v("tF"),size:+v("tS"),color:v("tC"),stroke_color:v("tSC"),stroke_width:+v("tSW"),line_spacing:+v("tLS"),max_lines:+v("tML"),align:v("tA")},
  plate:{enabled:v("pE"),color:v("pC"),opacity:+v("pO"),position:v("pP"),offset:+v("pOf"),padding:+v("pPd"),radius:+v("pR")},
  audio:{original:v("aO"),original_volume:+v("aOV"),music_volume:+v("aMV"),music_folder:v("aM")},timing:{text_start:+v("mS"),text_end:+v("mE"),max_total:+v("mT")}};
 const r=await api(id?"/recipes/"+id:"/recipes",{method:id?"PATCH":"POST",body:JSON.stringify(b)});
 const rows=parseRows(document.getElementById("xT").value);const old=(cur.texts||[]).map(x=>[x.text,x.title,x.description].filter((s,i)=>s||i===0).join(" | ")).join("\n");
 if(document.getElementById("xT").value.trim()!==old.trim())await api(`/recipes/${r.id}/texts`,{method:"PUT",body:JSON.stringify({rows,replace:true})});
 closeModal();A.tab="recipes";await page()}catch(e){fail(e)}finally{if(btn.isConnected)btn.disabled=false}};
window.asTextsUpload=async id=>{const f=document.getElementById("xF").files[0];if(!f)return fail(new Error("Выберите файл"));try{await localLogin;const fd=new FormData();fd.append("file",f);fd.append("replace","1");const r=await fetch(`/api/recipes/${id}/texts`,{method:"POST",headers:authHeaders(),body:fd});const x=await r.json();if(!r.ok)throw new Error(x.error||"Не загрузилось");await asForm(id);asSec("texts")}catch(e){fail(e)}};
window.asTextsReset=async id=>{await api(`/recipes/${id}/texts/reset`,{method:"POST",body:"{}"});await asForm(id);asSec("texts")};
window.asDel=async id=>{if(!confirm("Удалить рецепт? Очередь его задач будет отменена, готовые ролики останутся."))return;try{await api("/recipes/"+id,{method:"DELETE"});closeModal();await page()}catch(e){fail(e)}};
/* ---------- sources ---------- */
window.asSrcForm=async function(id){const [src,rs,acc]=await Promise.all([api("/sources"),api("/recipes"),api("/accounts")]);const s=src.find(x=>x.id===id)||{weight:1,active:1,start_per_day:1,target_per_day:3,ramp_days:7};
 if(!rs.length){modalBox('<h3>Сначала рецепт</h3><p>Создайте рецепт склейки, затем укажите, на какие аккаунты он публикует.</p><div class="row"><button class="btn" onclick="closeModal()">Понятно</button></div>');return}
 modalBox(`<h3>${id?"Источник":"Новый источник"}</h3><div class="form">
 <label>Аккаунт<select id="sA" ${id?"disabled":""}>${acc.map(a=>opt(a.id,a.platform+" · "+(a.username||"—")+(a.automation_ready?"":" (без автопубликации)"),s.account_id)).join("")}</select></label>
 <label>Рецепт склейки<select id="sR" ${id?"disabled":""}>${rs.map(r=>opt(r.id,r.name,s.recipe_id)).join("")}</select></label>
 <div class="formgrid"><label>Вес (1–10)<input id="sW" type="number" min="1" max="10" value="${s.weight}"></label><label class="ws-check" style="margin-top:28px"><input id="sAc" type="checkbox" ${s.active?"checked":""}> Активен</label></div>
 <div class="formgrid"><label>Старт: роликов в 1-й день<input id="sS" type="number" min="0" max="50" value="${s.start_per_day}"></label><label>Цель: роликов в день<input id="sT" type="number" min="1" max="50" value="${s.target_per_day}"></label></div>
 <label>Дней до цели<input id="sD" type="number" min="1" max="90" value="${s.ramp_days}"></label><p class="muted">Новым аккаунтам не стоит сразу выкладывать много — начните с 1 в день.</p>${errBox}
 <div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="asSrcSave('${id||""}')">Сохранить</button></div></div>`)};
window.asSrcSave=async id=>{try{const b={account_id:v("sA"),recipe_id:v("sR"),weight:+v("sW"),active:v("sAc"),start_per_day:+v("sS"),target_per_day:+v("sT"),ramp_days:+v("sD")};await api(id?"/sources/"+id:"/sources",{method:id?"PATCH":"POST",body:JSON.stringify(b)});closeModal();A.tab="sources";await page()}catch(e){fail(e)}};
window.asSrcDel=async id=>{if(!confirm("Удалить источник?"))return;await api("/sources/"+id,{method:"DELETE"});await page()};
routes.assembly=page;
const navEl=document.querySelector("nav");if(navEl&&!navEl.querySelector('[data-page="assembly"]')){const b=document.createElement("button");b.type="button";b.className="nav-item";b.dataset.page="assembly";b.innerHTML='<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h10M4 17h16"/><circle cx="18" cy="12" r="2"/></svg><span>Склейка</span>';b.onclick=()=>goPage("assembly");const ref=navEl.querySelector('[data-page="publishing"]');ref?ref.before(b):navEl.append(b)}
setInterval(()=>{if(document.hidden||modal.classList.contains("show"))return;if(document.querySelector("nav .nav-item.active")?.dataset.page==="assembly"&&A.tab==="jobs")page().catch(()=>{})},8000);
})();
