/* FaxClip «Прогрев»: rule-based warm-up sessions (no AI yet), scenarios, stages. */
(function(){
const TS={scheduled:["Запланирована",""],running:["Идёт сейчас",""],done:["Выполнена",""],failed:["Ошибка","red"],cancelled:["Отменена","red"],human_intervention:["Нужен человек","red"],missed:["Пропущена","red"]};
const SL={morning:"Утро",afternoon:"День",evening:"Вечер",night:"Ночь",manual:"Вручную"};
const MD={any:"Любой",young:"Молодой",warming:"Прогрев",hot:"Горячий"};
const W={tab:"sessions",status:""};
const fmt=t=>t?new Date(typeof t==="number"?t*1000:t).toLocaleString("ru-RU",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"—";
const pill=(m,s)=>{const [l,c]=m[s]||[s,""];return `<span class="pill"><i class="dot ${c}"></i>${l}</span>`};
const v=id=>{const e=document.getElementById(id);return e?(e.type==="checkbox"?e.checked:e.value.trim()):""};
const errBox='<p id="wsErr" class="ws-err" style="display:none"></p>';
const fail=e=>{const b=document.getElementById("wsErr");if(b){b.textContent=e.message||String(e);b.style.display="block"}else showAppError(e)};
const opt=(val,l,cur)=>`<option value="${esc(val)}" ${String(val)===String(cur)?"selected":""}>${esc(l)}</option>`;
const cnt=a=>{a=a||{};const p=[];if(a.videos)p.push("видео "+a.videos);if(a.likes)p.push("лайков "+a.likes);if(a.follows)p.push("подписок "+a.follows);if(a.searches)p.push("поисков "+a.searches);if(a.seconds)p.push(Math.round(a.seconds/60)+" мин");return p.join(" · ")};
async function page(){
 const [st,tasks,sc]=await Promise.all([api("/warmup/settings"),api("/warmup/tasks"+(W.status?"?status="+W.status:"")),api("/scenarios")]);
 const head=`<div class="row" style="flex-wrap:wrap;gap:10px;margin-bottom:12px"><div class="tabs ws-tabs" style="margin:0">${[["sessions","Сессии"],["scenarios","Сценарии "+sc.length],["settings","Настройки"]].map(([k,l])=>`<button class="${W.tab===k?"active":""}" onclick="wuTab('${k}')">${l}</button>`).join("")}</div>
 <div class="row" style="gap:8px">${st.enabled?'<span class="pill"><i class="dot"></i>Прогрев включён</span>':'<span class="pill"><i class="dot red"></i>Прогрев выключен</span>'}${st.agent_online?'<span class="pill"><i class="dot"></i>Mac на связи</span>':'<span class="pill"><i class="dot red"></i>Mac прогрева не на связи</span>'}</div></div>`;
 let html="";
 if(W.tab==="sessions"){const now=Date.now()/1000;const up=tasks.filter(t=>["scheduled","running"].includes(t.status)).sort((a,b)=>a.planned_start-b.planned_start),past=tasks.filter(t=>!["scheduled","running"].includes(t.status));
  const row=t=>`<div class="item row ws-post" onclick="wuOpen('${t.id}')" style="cursor:pointer"><div style="flex:1;min-width:0"><b>${esc(t.username||"—")}</b> <span class="muted">· ${esc(t.persona||"")} · ${esc(t.scenario||"")}</span><div class="muted">${SL[t.time_slot]||""} · ${fmt(t.planned_start)} · ${Math.round((t.duration||0)/60)} мин${cnt(t.actions)?" · "+cnt(t.actions):""}</div>${t.error?`<div class="muted" style="color:#ff8a8a">${esc(t.error)}</div>`:""}</div><div>${pill(TS,t.status)}</div></div>`;
  html=`${st.enabled?"":`<p class="ws-err" style="display:block">Прогрев выключен. Включите его во вкладке «Настройки» — до этого сессии не планируются и не выполняются.</p>`}
  <div class="row form ws-filter" style="gap:8px;margin-bottom:10px;justify-content:flex-start"><select onchange="wuFilter(this.value)">${opt("","Все статусы",W.status)}${Object.entries(TS).map(([k,[l]])=>opt(k,l,W.status)).join("")}</select><button class="btn secondary" onclick="wuRunForm()">Запустить сессию сейчас</button></div>
  <div class="card ws-posts"><b>Ближайшие</b><div class="list">${up.map(row).join("")||'<div class="empty">Нет запланированных сессий</div>'}</div></div>
  <div class="card ws-posts" style="margin-top:14px"><b>История</b><div class="list">${past.slice(0,60).map(row).join("")||'<div class="empty">Пока пусто</div>'}</div></div>`}
 if(W.tab==="scenarios")html=`<div class="card"><p class="muted">Сценарий — правила сессии: сколько смотреть видео, как часто ставить лайк и подписываться, искать ли по ключевым словам аккаунта. «Прогрев 1/2/3» — системные шаблоны для ступеней «Молодой», «Прогрев», «Горячий». Комментарии появятся вместе с ИИ.</p>
  <table class="table"><thead><tr><th>Сценарий</th><th>Ступень</th><th>Длительность</th><th>Просмотр</th><th>Лайки</th><th>Подписки</th><th>Поиск</th><th>Итог</th><th></th></tr></thead><tbody>${sc.map(s=>`<tr><td><b>${esc(s.name)}</b>${s.system?'<br><span class="muted">системный</span>':""}</td><td>${MD[s.account_mode]}</td><td>до ${s.max_duration} мин</td><td>${s.watch_min}–${s.watch_max} с</td><td>${s.like_pct}% · макс ${s.max_likes}</td><td>${s.follow_pct}% · макс ${s.max_follows}</td><td>${s.search_pct}%</td><td class="muted">✓${s.num_success} ✗${s.num_fail}</td><td>${s.system?`<button class="btn secondary" onclick="wuScForm('${s.id}',true)">Копировать</button>`:`<button class="btn secondary" onclick="wuScForm('${s.id}')">Изменить</button> <button class="btn secondary" onclick="wuScDel('${s.id}')">Удалить</button>`}</td></tr>`).join("")}</tbody></table></div>`;
 if(W.tab==="settings")html=`<div class="card"><div class="form">
  <label class="ws-check"><input id="wE" type="checkbox" ${st.enabled?"checked":""}> Прогрев включён — сессии планируются по слотам активности персон</label>
  <label class="ws-check"><input id="wA" type="checkbox" ${st.auto_stage_promotion?"checked":""}> Автоповышение ступени по числу успешных сессий</label>
  <div class="formgrid"><label>«Молодой» → «Прогрев» после сессий<input id="wTW" type="number" min="1" value="${st.to_warming}"></label><label>«Прогрев» → «Горячий» после сессий<input id="wTH" type="number" min="2" value="${st.to_hot}"></label></div>
  <label>Часовой пояс по умолчанию<input id="wTZ" value="${esc(st.timezone)}" placeholder="Europe/Moscow"></label><p class="muted">Свой часовой пояс можно задать телефону в «Устройства» → «Настройки».</p>
  ${errBox}<div class="row" style="justify-content:flex-start;gap:8px"><button class="btn" onclick="wuSaveSettings()">Сохранить</button><button class="btn secondary" onclick="wuInstall()">Установить прогрев на Mac</button></div></div></div>
  <div class="card" style="margin-top:14px"><b>Кто будет прогреваться</b><p class="muted">Нужны: TikTok-аккаунт на телефоне, активная персона на этом же телефоне, статус аккаунта «В системе», ступень не «Спящий».</p><div class="list">${st.eligible.map(e=>`<div class="item row"><span><b>${esc(e.username)}</b> <span class="muted">· ${esc(e.persona)} · ${MD[e.work_mode]||"Молодой"}</span></span></div>`).join("")||'<div class="empty">Пока нет подходящих аккаунтов — проверьте персону и аккаунт.</div>'}</div>
  <p class="muted">Важно: на телефоне должен быть открыт именно этот аккаунт TikTok, а экран — без пароля (или телефон разблокирован). Если TikTok покажет капчу, сессия остановится и придёт уведомление «Нужен человек».</p></div>`;
 shell("Прогрев","Сессии в TikTok по расписанию персон — без ИИ",head+html,W.tab==="scenarios"?`<button class="btn" onclick="wuScForm()">+ Сценарий</button>`:"")}
window.wuTab=t=>{W.tab=t;page().catch(showAppError)};
window.wuFilter=s=>{W.status=s;page().catch(showAppError)};
window.wuOpen=async id=>{const t=await api("/warmup/tasks/"+id);const b=[];
 if(["scheduled","running"].includes(t.status))b.push(`<button class="btn secondary" onclick="wuAct('${id}','cancel')">Отменить</button>`);
 if(["cancelled","human_intervention","failed","missed"].includes(t.status))b.push(`<button class="btn" onclick="wuAct('${id}','restart')">Перезапустить сейчас</button>`);
 if(["scheduled","failed","cancelled","human_intervention","missed"].includes(t.status))b.push(`<button class="btn secondary" onclick="wuAct('${id}','delete')">Удалить</button>`);
 modalBox(`<h3>Сессия · ${esc(t.username||"")}</h3><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">${pill(TS,t.status)}<span class="muted">${esc(t.scenario||"")} · ${SL[t.time_slot]||""} · ${fmt(t.planned_start)} · ${Math.round((t.duration||0)/60)} мин</span></div>
 ${cnt(t.actions)?`<p>${cnt(t.actions)}</p>`:""}${t.error?`<p class="ws-err" style="display:block">${esc(t.error)}</p>`:""}
 <div class="list" style="max-height:340px;overflow:auto">${t.events.map(e=>`<div class="item row"><span>${esc(e.message)}</span><span class="muted">${new Date(e.created_at).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</span></div>`).join("")||'<div class="empty">Событий пока нет</div>'}</div>${errBox}
 <div class="row" style="gap:8px;flex-wrap:wrap;justify-content:flex-end"><button class="close" onclick="closeModal()">Закрыть</button>${b.join("")}</div>`)};
window.wuAct=async(id,a)=>{if(a==="delete"&&!confirm("Удалить сессию?"))return;try{await api(`/warmup/tasks/${id}/${a}`,{method:"POST",body:"{}"});closeModal();await page()}catch(e){fail(e)}};
window.wuRunForm=async()=>{const [st,sc]=await Promise.all([api("/warmup/settings"),api("/scenarios")]);
 if(!st.eligible.length){modalBox('<h3>Нет аккаунтов для прогрева</h3><p>Нужен TikTok-аккаунт с персоной на том же телефоне и статусом «В системе». Настройте это в «Аккаунты» и «Персоны».</p><div class="row"><button class="btn" onclick="closeModal()">Понятно</button></div>');return}
 modalBox(`<h3>Сессия сейчас</h3><div class="form"><label>Аккаунт<select id="rA">${st.eligible.map(e=>opt(e.account_id,e.username+" · "+e.persona)).join("")}</select></label>
 <label>Сценарий<select id="rS"><option value="">По ступени аккаунта</option>${sc.map(s=>opt(s.id,s.name+" ("+MD[s.account_mode]+")")).join("")}</select></label><label>Минут<input id="rM" type="number" min="3" max="60" value="10"></label>
 ${st.enabled?"":'<p class="ws-err" style="display:block">Прогрев выключен — сессия начнётся, когда включите его в «Настройках».</p>'}${st.agent_online?"":'<p class="muted">Mac прогрева не на связи — установите его в «Настройках».</p>'}${errBox}
 <div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="wuRunGo()">Запустить</button></div></div>`)};
window.wuRunGo=async()=>{try{await api("/warmup/run-now",{method:"POST",body:JSON.stringify({account_id:v("rA"),scenario_id:v("rS")||null,minutes:+v("rM")||10})});closeModal();W.tab="sessions";await page()}catch(e){fail(e)}};
window.wuSaveSettings=async()=>{try{await api("/warmup/settings",{method:"PUT",body:JSON.stringify({enabled:v("wE"),auto_stage_promotion:v("wA"),to_warming:+v("wTW"),to_hot:+v("wTH"),timezone:v("wTZ")})});await page();modalBox('<h3>Сохранено</h3><div class="row"><button class="btn" onclick="closeModal()">Понятно</button></div>')}catch(e){fail(e)}};
window.wuInstall=async()=>{let cmd="";try{cmd=(await api("/warm-install-command")).command}catch(e){}
 modalBox(`<h3>Прогрев на Mac</h3><p>Сессии выполняет ваш Mac через USB, как и публикации. Откройте «Терминал», вставьте команду и нажмите Enter.</p>${cmd?`<textarea readonly rows="5" style="width:100%;font-family:monospace;font-size:12px" onclick="this.select()">${esc(cmd)}</textarea>`:'<p class="ws-err" style="display:block">Команда пока недоступна.</p>'}<div class="row"><button class="btn secondary" onclick="navigator.clipboard.writeText(this.closest('div').previousElementSibling.value).then(()=>this.textContent='Скопировано')">Скопировать</button><button class="btn" onclick="closeModal()">Готово</button></div>`)};
window.wuScForm=async(id,copy)=>{const s=(await api("/scenarios")).find(x=>x.id===id)||{name:"",account_mode:"any",max_duration:15,watch_min:5,watch_max:20,like_pct:10,follow_pct:0,search_pct:30,max_likes:10,max_follows:0};
 const edit=id&&!copy;modalBox(`<h3>${edit?"Сценарий":"Новый сценарий"}</h3><div class="form"><label>Название<input id="sN" value="${esc(copy?s.name+" (копия)":s.name)}"></label>
 <div class="formgrid"><label>Для ступени<select id="sM">${Object.entries(MD).map(([k,l])=>opt(k,l,s.account_mode)).join("")}</select></label><label>Макс. длительность, мин<input id="sD" type="number" min="3" max="60" value="${s.max_duration}"></label></div>
 <div class="formgrid"><label>Смотреть видео от, сек<input id="sW1" type="number" min="2" value="${s.watch_min}"></label><label>до, сек<input id="sW2" type="number" min="2" value="${s.watch_max}"></label></div>
 <div class="formgrid"><label>Лайк, % видео<input id="sL" type="number" min="0" max="60" value="${s.like_pct}"></label><label>Макс. лайков за сессию<input id="sLM" type="number" min="0" max="100" value="${s.max_likes}"></label></div>
 <div class="formgrid"><label>Подписка, % видео<input id="sF" type="number" min="0" max="20" value="${s.follow_pct}"></label><label>Макс. подписок за сессию<input id="sFM" type="number" min="0" max="30" value="${s.max_follows}"></label></div>
 <label>Поиск по ключевым словам аккаунта, % сессий<input id="sS" type="number" min="0" max="100" value="${s.search_pct}"></label>${errBox}
 <div class="row"><button class="close" onclick="closeModal()">Отмена</button><button class="btn" onclick="wuScSave('${edit?id:""}')">Сохранить</button></div></div>`)};
window.wuScSave=async id=>{try{const b={name:v("sN"),account_mode:v("sM"),max_duration:+v("sD"),watch_min:+v("sW1"),watch_max:+v("sW2"),like_pct:+v("sL"),max_likes:+v("sLM"),follow_pct:+v("sF"),max_follows:+v("sFM"),search_pct:+v("sS")};await api(id?"/scenarios/"+id:"/scenarios",{method:id?"PATCH":"POST",body:JSON.stringify(b)});closeModal();await page()}catch(e){fail(e)}};
window.wuScDel=async id=>{if(!confirm("Удалить сценарий?"))return;try{await api("/scenarios/"+id,{method:"DELETE"});await page()}catch(e){showAppError(e)}};
routes.warmup=page;
const navEl=document.querySelector("nav");if(navEl&&!navEl.querySelector('[data-page="warmup"]')){const b=document.createElement("button");b.type="button";b.className="nav-item";b.dataset.page="warmup";b.innerHTML='<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3c2 3 5 5 5 9a5 5 0 0 1-10 0c0-2 1-3 2-4 0 2 1 3 2 3 0-3-1-5 1-8z"/></svg><span>Прогрев</span>';b.onclick=()=>goPage("warmup");const ref=navEl.querySelector('[data-page="assembly"]')||navEl.querySelector('[data-page="publishing"]');ref?ref.before(b):navEl.append(b)}
setInterval(()=>{if(document.hidden||modal.classList.contains("show"))return;if(document.querySelector("nav .nav-item.active")?.dataset.page==="warmup"&&W.tab==="sessions")page().catch(()=>{})},10000);
})();
