import base64,hashlib
from pathlib import Path
src=Path('bridge/render_agent.py').read_bytes()
tpl=r'''# FaxClip render installer (generated by tools/build_render_installer.py). Installs the Mac video assembly agent.
import base64,hashlib,os,plistlib,subprocess,sys,time
from pathlib import Path
AGENT_B64="__B64__"
AGENT_SHA="__SHA__"
LABEL='com.faxclip.render';MANAGER='com.faxclip.devices'
def main():
    home=Path.home();python=sys.executable;root=home/'Downloads/faxclip-telegram-bridge-v14'
    mp=home/'Library/LaunchAgents'/(MANAGER+'.plist')
    if mp.exists():
        try:
            args=plistlib.loads(mp.read_bytes()).get('ProgramArguments',[])
            if len(args)>=4 and args[2]=='--root':python=args[0];root=Path(args[3])
        except Exception:pass
    if not list((root/'.faxclip-cloud/devices').glob('*.json')):raise SystemExit('Телефон ещё не подключён к FaxClip. Сначала подключите его по коду.')
    src=base64.b64decode(AGENT_B64)
    if hashlib.sha256(src).hexdigest()!=AGENT_SHA:raise SystemExit('Файл повреждён. Ничего не установлено.')
    print('Ставлю компоненты для монтажа (ffmpeg, Pillow)… 1–3 минуты.',flush=True)
    chk=subprocess.run([python,'-c','import PIL,imageio_ffmpeg;imageio_ffmpeg.get_ffmpeg_exe()'],capture_output=True)
    if chk.returncode:
        r=subprocess.run([python,'-m','pip','install','--quiet','--disable-pip-version-check','pillow>=10','imageio-ffmpeg>=0.5'],capture_output=True,text=True)
        if r.returncode:raise SystemExit('Не удалось установить компоненты. Проверьте интернет и повторите. '+(r.stderr or '')[-300:])
        chk=subprocess.run([python,'-c','import PIL,imageio_ffmpeg;print(imageio_ffmpeg.get_ffmpeg_exe())'],capture_output=True,text=True)
        if chk.returncode:raise SystemExit('ffmpeg не запустился: '+(chk.stderr or '')[-300:])
    dest=home/'Library/Application Support/FaxClip Render';dest.mkdir(parents=True,exist_ok=True)
    agent=dest/'render_agent.py';agent.write_bytes(src);agent.chmod(0o644)
    base=home/'Downloads/FaxClip/Склейка'
    if not base.exists():
        for f in ('intro','main','outro','music'):(base/f).mkdir(parents=True,exist_ok=True)
        (base/'КАК ПОЛЬЗОВАТЬСЯ.txt').write_text('Каждая подпапка — сцена. Положите в неё 3–5 дублей (mp4/mov).\nFaxClip возьмёт по одному случайному дублю из каждой сцены и склеит ролик.\nВ music — треки (mp3/m4a), берётся случайный.\nИмена папок впишите в рецепт в Mini App → Склейка.\n',encoding='utf-8')
    logs=home/'Library/Logs/FaxClip';logs.mkdir(parents=True,exist_ok=True);log=logs/'render.log'
    if log.exists():log.unlink()
    plist=home/'Library/LaunchAgents'/(LABEL+'.plist');plist.parent.mkdir(parents=True,exist_ok=True)
    plist.write_bytes(plistlib.dumps({'Label':LABEL,'ProgramArguments':[python,str(agent),'--root',str(root)],'RunAtLoad':True,'KeepAlive':True,
        'ProcessType':'Background','LowPriorityIO':True,'Nice':5,'StandardOutPath':str(log),'StandardErrorPath':str(log)}))
    uid=os.getuid()
    subprocess.run(['launchctl','bootout',f'gui/{uid}/{LABEL}'],capture_output=True)
    time.sleep(1)
    r=subprocess.run(['launchctl','bootstrap',f'gui/{uid}',str(plist)],capture_output=True,text=True)
    if r.returncode:subprocess.run(['launchctl','kickstart','-k',f'gui/{uid}/{LABEL}'],capture_output=True)
    for _ in range(20):
        time.sleep(1)
        if log.exists() and 'RENDER_AGENT_V1 started' in log.read_text(errors='replace'):
            print('ГОТОВО. Склейка установлена. Папки для сцен: Загрузки/FaxClip/Склейка. Mini App → Склейка.');return
    tail=log.read_text(errors='replace')[-400:] if log.exists() else ''
    raise SystemExit('Склейка установлена, но не запустилась. Пришлите этот текст: '+tail.replace('\n',' | '))
main()
'''
out=tpl.replace('__B64__',base64.b64encode(src).decode()).replace('__SHA__',hashlib.sha256(src).hexdigest())
Path('bridge/render_install.py').write_text(out);print('built',hashlib.sha256(src).hexdigest())
