import base64,hashlib
from pathlib import Path
src=Path('bridge/screen_agent.py').read_bytes()
tpl=r'''# FaxClip screen installer (generated by tools/build_screen_installer.py). Installs the Mac screen agent as a LaunchAgent.
import base64,hashlib,os,plistlib,subprocess,sys,time
from pathlib import Path
AGENT_B64="__B64__"
AGENT_SHA="__SHA__"
LABEL='com.faxclip.screen';MANAGER='com.faxclip.devices'
def main():
    home=Path.home();python=sys.executable;root=home/'Downloads/faxclip-telegram-bridge-v14'
    mp=home/'Library/LaunchAgents'/(MANAGER+'.plist')
    if mp.exists():
        try:
            args=plistlib.loads(mp.read_bytes()).get('ProgramArguments',[])
            if len(args)>=4 and args[2]=='--root':python=args[0];root=Path(args[3])
        except Exception:pass
    if not (root/'platform-tools/adb').exists():raise SystemExit('Папка моста FaxClip не найдена. Ничего не установлено.')
    if not list((root/'.faxclip-cloud/devices').glob('*.json')):raise SystemExit('Телефон ещё не подключён к FaxClip. Сначала подключите его по коду.')
    src=base64.b64decode(AGENT_B64)
    if hashlib.sha256(src).hexdigest()!=AGENT_SHA:raise SystemExit('Файл повреждён. Ничего не установлено.')
    dest=home/'Library/Application Support/FaxClip Screen';dest.mkdir(parents=True,exist_ok=True)
    agent=dest/'screen_agent.py';agent.write_bytes(src);agent.chmod(0o644)
    logs=home/'Library/Logs/FaxClip';logs.mkdir(parents=True,exist_ok=True);log=logs/'screen.log'
    if log.exists():log.unlink()
    plist=home/'Library/LaunchAgents'/(LABEL+'.plist');plist.parent.mkdir(parents=True,exist_ok=True)
    plist.write_bytes(plistlib.dumps({'Label':LABEL,'ProgramArguments':[python,str(agent),'--root',str(root)],'RunAtLoad':True,'KeepAlive':True,
        'StandardOutPath':str(log),'StandardErrorPath':str(log)}))
    uid=os.getuid()
    subprocess.run(['launchctl','bootout',f'gui/{uid}/{LABEL}'],capture_output=True)
    time.sleep(1)
    r=subprocess.run(['launchctl','bootstrap',f'gui/{uid}',str(plist)],capture_output=True,text=True)
    if r.returncode:subprocess.run(['launchctl','kickstart','-k',f'gui/{uid}/{LABEL}'],capture_output=True)
    for _ in range(15):
        time.sleep(1)
        if log.exists() and 'SCREEN_AGENT_V1 started' in log.read_text(errors='replace'):
            print('ГОТОВО. Экран телефона установлен: Mini App → Устройства → Экран.');return
    tail=log.read_text(errors='replace')[-400:] if log.exists() else ''
    raise SystemExit('Экран установлен, но не запустился. Пришлите этот текст: '+tail.replace('\n',' | '))
main()
'''
out=tpl.replace('__B64__',base64.b64encode(src).decode()).replace('__SHA__',hashlib.sha256(src).hexdigest())
Path('bridge/screen_install.py').write_text(out);print('built',hashlib.sha256(src).hexdigest())
